// tienda-frontend/src/pages/ProductDetail.tsx
import { useEffect, useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { useCart } from '../context/CartContext';
import { useAuth } from '../context/AuthContext';
import { productsAPI } from '../services/api';
import { ReviewsList } from '../components/ReviewsList';
import { getProductImage, getProductImages } from '../utils/productImages';
import type { Product } from '../types';

interface ExtendedProduct extends Product {
  features: string[];
}

const ProductDetail = () => {
  const { id } = useParams<{ id: string }>();
  const [product, setProduct] = useState<ExtendedProduct | null>(null);
  const [selectedSize, setSelectedSize] = useState('M');
  const [quantity, setQuantity] = useState(1);
  const [activeImage, setActiveImage] = useState(0);
  const [isAddingToCart, setIsAddingToCart] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { addToCart } = useCart();
  const { user } = useAuth();
  const navigate = useNavigate();

  // Generar galería de imágenes apropiadas para el producto
  const productImages = product ? getProductImages(product.name, product.category, 4) : [];

  const sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

  useEffect(() => {
    const fetchProduct = async () => {
      if (!id) {
        navigate('/products');
        return;
      }

      try {
        setLoading(true);
        console.log('🔄 Fetching product details for ID:', id);
        const response = await productsAPI.getById(parseInt(id));
        console.log('✅ Product details fetched:', response.data);
        
        // Procesar datos del backend y agregar características por defecto
        const backendProduct = response.data.data || response.data;
        const extendedProduct: ExtendedProduct = {
          id: backendProduct.id,
          name: backendProduct.name?.replace(/�/g, 'á').replace(/�/g, 'ó').replace(/�/g, 'í') || backendProduct.name,
          description: backendProduct.description?.replace(/�/g, 'á').replace(/�/g, 'ó').replace(/�/g, 'í') || backendProduct.description,
          price: backendProduct.price || 0,
          category: backendProduct.category || 'general',
          stock: backendProduct.stock || 0,
          imageUrl: getProductImage(backendProduct.name, backendProduct.category, backendProduct.imageUrl),
          features: (backendProduct as any).features || [
            "Material de alta calidad",
            "Diseño moderno y elegante",
            "Cómodo para uso diario",
            "Fácil cuidado y mantenimiento",
            "Disponible en múltiples tallas"
          ]
        };
        
        setProduct(extendedProduct);
        setError(null);
      } catch (err) {
        console.error('❌ Error fetching product details:', err);
        setError('Error al cargar los detalles del producto. Redirigiendo...');
        
        // Redirigir a la página de productos después de 2 segundos
        setTimeout(() => navigate('/products'), 2000);
      } finally {
        setLoading(false);
      }
    };

    fetchProduct();
  }, [id, navigate]);

  const handleAddToCart = async () => {
    if (!product) return;
    
    setIsAddingToCart(true);
    await new Promise(resolve => setTimeout(resolve, 800)); // Simulate API call
    
    for (let i = 0; i < quantity; i++) {
      addToCart(product);
    }
    
    setIsAddingToCart(false);
  };

  // Loading state
  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-purple-400 mx-auto mb-4"></div>
          <p className="text-xl text-gray-300">Cargando detalles del producto...</p>
        </div>
      </div>
    );
  }

  // Error state
  if (error && !product) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center px-4">
        <div className="text-center">
          <div className="text-8xl mb-4">😞</div>
          <h2 className="text-3xl font-bold text-white mb-2">Error al cargar el producto</h2>
          <p className="text-gray-300 mb-6 text-lg">{error}</p>
          <Link
            to="/products"
            className="inline-block bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white px-8 py-3 rounded-lg font-semibold transition-all transform hover:scale-105 shadow-lg"
          >
            ← Volver a productos
          </Link>
        </div>
      </div>
    );
  }

  // Product not found
  if (!product) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center px-4">
        <div className="text-center">
          <div className="text-8xl mb-4">🔍</div>
          <h2 className="text-3xl font-bold text-white mb-2">Producto no encontrado</h2>
          <p className="text-gray-300 mb-6 text-lg">El producto que buscas no existe o ha sido eliminado.</p>
          <Link
            to="/products"
            className="inline-block bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white px-8 py-3 rounded-lg font-semibold transition-all transform hover:scale-105 shadow-lg"
          >
            ← Volver a productos
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 py-16 px-4">
      {/* Floating Gradient Orbs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
      </div>

      <div className="max-w-7xl mx-auto px-4 relative z-10">
        {/* Breadcrumb */}
        <nav className="mb-8 animate-fade-in-up">
          <div className="flex items-center space-x-2 text-gray-300">
            <Link to="/" className="hover:text-purple-300 transition-colors">🏠 Inicio</Link>
            <span className="text-gray-400">›</span>
            <Link to="/products" className="hover:text-purple-300 transition-colors">Productos</Link>
            <span className="text-gray-400">›</span>
            <span className="text-white font-medium">{product.name}</span>
          </div>
        </nav>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Product Images */}
          <div className="space-y-4 animate-fade-in-up">
            <div className="relative overflow-hidden rounded-2xl shadow-2xl">
              <img
                src={productImages[activeImage] || product.imageUrl}
                alt={product.name}
                className="w-full h-96 lg:h-[600px] object-cover"
              />
              <div className="absolute top-4 right-4">
                <span className="bg-gradient-secondary text-white px-4 py-2 rounded-full font-semibold shadow-lg">
                  ⭐ Nuevo
                </span>
              </div>
            </div>
            
            {/* Thumbnail Images */}
            <div className="flex gap-4">
              {productImages.map((img, index) => (
                <button
                  key={index}
                  onClick={() => setActiveImage(index)}
                  className={`w-20 h-20 rounded-lg overflow-hidden border-2 transition-all duration-300 ${
                    activeImage === index 
                      ? 'border-purple-400 shadow-lg shadow-purple-500/50' 
                      : 'border-white/20 hover:border-purple-400'
                  }`}
                >
                  <img
                    src={img || product.imageUrl}
                    alt={`${product.name} ${index + 1}`}
                    className="w-full h-full object-cover"
                  />
                </button>
              ))}
            </div>
          </div>

          {/* Product Info */}
          <div className="space-y-6 animate-fade-in-up">
            <div>
              <h1 className="text-5xl font-black text-white mb-4">
                {product.name}
              </h1>
              <div className="flex items-center gap-4 mb-6 flex-wrap">
                <span className="text-4xl font-black text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text">
                  S/ {Number(product.price).toFixed(2)}
                </span>
                <span className="bg-green-500/30 text-green-200 px-4 py-2 rounded-full text-sm font-bold border border-green-400/50 backdrop-blur-sm">
                  ✅ En stock ({product.stock || 0} disponibles)
                </span>
              </div>
              <p className="text-gray-300 text-lg leading-relaxed">
                {product.description}
              </p>
            </div>

            {/* Size Selection */}
            <div>
              <h3 className="text-lg font-bold text-white mb-4">
                📏 Talla
              </h3>
              <div className="flex gap-2">
                {sizes.map(size => (
                  <button
                    key={size}
                    onClick={() => setSelectedSize(size)}
                    className={`w-12 h-12 rounded-lg border-2 font-bold transition-all duration-300 ${
                      selectedSize === size
                        ? 'border-purple-400 bg-gradient-to-r from-purple-600 to-pink-600 text-white shadow-lg shadow-purple-500/50'
                        : 'border-white/30 text-white hover:border-purple-400 hover:bg-white/10'
                    }`}
                  >
                    {size}
                  </button>
                ))}
              </div>
            </div>

            {/* Quantity Selection */}
            <div>
              <h3 className="text-lg font-bold text-white mb-4">
                🔢 Cantidad
              </h3>
              <div className="flex items-center gap-4 bg-white/10 rounded-lg p-3 border border-white/20 w-fit">
                <button
                  onClick={() => setQuantity(Math.max(1, quantity - 1))}
                  className="w-10 h-10 rounded-full bg-purple-600/50 hover:bg-purple-600 text-white transition-all flex items-center justify-center font-bold text-lg"
                >
                  −
                </button>
                <span className="text-2xl font-black text-white px-6">{quantity}</span>
                <button
                  onClick={() => setQuantity(Math.min(product.stock || 0, quantity + 1))}
                  className="w-10 h-10 rounded-full bg-pink-600/50 hover:bg-pink-600 text-white transition-all flex items-center justify-center font-bold text-lg"
                >
                  +
                </button>
              </div>
            </div>

            {/* Add to Cart Button */}
            <div className="space-y-4">
              <button
                onClick={handleAddToCart}
                disabled={isAddingToCart}
                className="w-full bg-gradient-primary text-white py-4 rounded-2xl font-bold text-lg hover:shadow-lg transform hover:scale-105 transition-all duration-300 btn-modern disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isAddingToCart ? (
                  <span className="flex items-center justify-center gap-2">
                    ⏳ Agregando al carrito...
                  </span>
                ) : (
                  <span className="flex items-center justify-center gap-2">
                    🛒 Agregar al carrito (S/ {(Number(product.price) * quantity).toFixed(2)})
                  </span>
                )}
              </button>
              
              <button className="w-full bg-gradient-success text-white py-4 rounded-2xl font-bold text-lg hover:shadow-lg transform hover:scale-105 transition-all duration-300 btn-modern">
                💳 Comprar ahora
              </button>
            </div>

            {/* Product Features */}
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-6">
              <h3 className="text-lg font-bold text-white mb-4">
                ✨ Características
              </h3>
              <ul className="space-y-3">
                {product.features.map((feature: string, index: number) => (
                  <li key={index} className="flex items-center gap-3 text-gray-200">
                    <span className="text-green-400 font-bold text-lg">✓</span>
                    <span className="font-medium">{feature}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Shipping Info */}
            <div className="bg-gradient-to-br from-blue-600/20 to-cyan-600/20 border border-white/20 backdrop-blur-md rounded-2xl p-6">
              <h3 className="text-lg font-bold text-white mb-4">
                🚚 Información de envío
              </h3>
              <div className="space-y-3 text-gray-200">
                <p className="flex items-center gap-2"><span>🎁</span> Envío gratis en compras mayores a S/ 150</p>
                <p className="flex items-center gap-2"><span>📦</span> Entrega en 2-3 días hábiles</p>
                <p className="flex items-center gap-2"><span>🔄</span> Devoluciones gratis hasta 30 días</p>
                <p className="flex items-center gap-2"><span>🛡️</span> Compra protegida 100%</p>
              </div>
            </div>
          </div>
        </div>

        {/* Reviews Section */}
        <div className="mt-8 bg-white rounded-2xl shadow-lg overflow-hidden">
          <div className="p-8">
            <ReviewsList
              productId={product.id}
              productName={product.name}
              currentUserId={user?.id}
              onReviewAdded={() => {
                // No necesitamos recargar la página, el componente ReviewsList
                // ya se encarga de recargar las reviews automáticamente
                console.log('✅ Review agregada, la lista se actualizará automáticamente');
              }}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProductDetail;

// tienda-frontend/tienda-vue/src/pages/ProductDetail.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 py-8">
    <div class="fixed inset-0 overflow-hidden pointer-events-none">
      <div class="absolute top-40 -right-40 w-80 h-80 bg-purple-500/10 rounded-full blur-3xl"></div>
      <div class="absolute bottom-40 -left-40 w-80 h-80 bg-pink-500/10 rounded-full blur-3xl"></div>
    </div>

    <div class="max-w-7xl mx-auto px-4 relative z-10">
      <!-- Breadcrumb -->
      <div class="mb-6 animate-fade-in-up">
        <RouterLink to="/products" class="text-purple-400 hover:text-purple-300 hover:underline transition-colors inline-flex items-center gap-2">
          ← Volver a productos
        </RouterLink>
      </div>

      <div v-if="loading" class="grid grid-cols-1 lg:grid-cols-2 gap-12">
          <div class="animate-pulse space-y-4">
            <div class="aspect-square bg-white/10 rounded-2xl"></div>
            <div class="grid grid-cols-4 gap-4">
              <div v-for="i in 4" :key="i" class="aspect-square bg-white/5 rounded-lg"></div>
            </div>
          </div>
          <div class="space-y-6 animate-pulse">
            <div class="h-8 bg-white/10 rounded w-1/3"></div>
            <div class="h-12 bg-white/10 rounded w-3/4"></div>
            <div class="h-10 bg-white/10 rounded w-1/4"></div>
            <div class="h-20 bg-white/5 rounded w-full"></div>
          </div>
        </div>

      <div v-else-if="!product" class="text-center py-20 animate-fade-in-up">
        <div class="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl p-12 max-w-lg mx-auto">
          <div class="text-8xl mb-6">😕</div>
          <h2 class="text-3xl font-bold text-white mb-4">Producto no encontrado</h2>
          <p class="text-gray-300 mb-8">El producto que buscas no existe o fue eliminado.</p>
          <RouterLink to="/products" class="inline-block px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-full font-bold hover:from-purple-700 hover:to-pink-700 transition-all transform hover:scale-105">
            ← Ver Productos
          </RouterLink>
        </div>
      </div>

      <div v-else>
        <!-- Product Main Info -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 mb-12">
          <!-- Images -->
          <div class="space-y-4 animate-scale-in">
            <div class="aspect-square bg-white/10 rounded-2xl overflow-hidden flex items-center justify-center border border-white/20 hover:border-purple-500/50 transition-all duration-300 group">
              <span class="text-9xl transform group-hover:scale-110 group-hover:rotate-6 transition-all duration-500">{{ getProductEmoji(product) }}</span>
            </div>
            <div class="grid grid-cols-4 gap-4">
              <div 
                v-for="i in 4" 
                :key="i"
                class="aspect-square bg-white/10 rounded-lg flex items-center justify-center border border-white/20 hover:border-purple-500/50 hover:scale-105 transition-all duration-300 cursor-pointer"
              >
                <span class="text-3xl transform hover:rotate-12 transition-transform duration-300">{{ getProductEmoji(product) }}</span>
              </div>
            </div>
          </div>

          <!-- Product Info -->
          <div class="space-y-6 animate-fade-in-up" style="animation-delay: 0.2s;">
            <div>
              <span class="inline-block px-3 py-1 bg-purple-500/30 text-purple-300 rounded-full text-sm mb-4 animate-pulse">
                {{ product.category }}
              </span>
              <h1 class="text-4xl md:text-5xl font-black text-white mb-4 hover:text-purple-400 transition-colors">{{ product.name }}</h1>
              <div class="flex items-center gap-4 flex-wrap">
                <span class="text-3xl md:text-4xl font-bold text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text">
                  S/ {{ Number(product.price).toFixed(2) }}
                </span>
                <div v-if="product.reviewCount" class="flex items-center gap-2 bg-white/10 px-3 py-1 rounded-full">
                  <div class="flex items-center">
                    <span class="text-yellow-400 text-xl">★</span>
                    <span class="text-white font-semibold ml-1">{{ Number(product.averageRating || 0).toFixed(1) }}</span>
                  </div>
                  <span class="text-gray-400">({{ product.reviewCount }} reseñas)</span>
                </div>
              </div>
              <div class="mt-4 flex items-center gap-2">
                <span v-if="product.stock > 0" class="text-green-400 flex items-center gap-2">
                  <span class="w-3 h-3 bg-green-400 rounded-full animate-pulse"></span>
                  En stock ({{ product.stock }} disponibles)
                </span>
                <span v-else class="text-red-400 flex items-center gap-2">
                  <span class="w-3 h-3 bg-red-400 rounded-full"></span>
                  Agotado
                </span>
              </div>
            </div>

            <p class="text-gray-300 text-lg leading-relaxed border-l-4 border-purple-500 pl-4">{{ product.description }}</p>

            <!-- Quantity & Add to Cart -->
            <div class="flex items-center gap-4 flex-wrap">
              <div class="flex items-center border border-white/20 rounded-xl bg-white/5">
                <button @click="quantity > 1 && quantity--" class="px-4 py-3 text-white hover:bg-white/10 transition-colors rounded-l-xl">−</button>
                <span class="px-6 py-3 text-white font-semibold border-x border-white/10">{{ quantity }}</span>
                <button @click="quantity++" class="px-4 py-3 text-white hover:bg-white/10 transition-colors rounded-r-xl">+</button>
              </div>
              <button 
                @click="addToCart" 
                :disabled="product.stock <= 0"
                class="flex-1 bg-gradient-to-r from-purple-600 to-pink-600 text-white py-3 px-6 rounded-xl font-bold hover:from-purple-700 hover:to-pink-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-105 hover:shadow-lg"
              >
                🛒 Agregar al Carrito
              </button>
              <button 
                @click="toggleWishlist"
                class="p-3 border border-white/20 rounded-xl text-white hover:bg-white/10 hover:border-purple-500/50 transition-all transform hover:scale-105"
              >
                {{ isInWishlist ? '❤️' : '🤍' }} {{ isInWishlist ? 'Favorito' : 'Favoritos' }}
              </button>
            </div>

            <!-- Product Details -->
            <div class="bg-white/5 rounded-xl p-6 space-y-3 border border-white/10 hover:border-purple-500/30 transition-all">
              <h3 class="text-white font-semibold text-lg flex items-center gap-2">
                <span>📋</span> Detalles del Producto
              </h3>
              <div class="grid grid-cols-2 gap-2 text-sm">
                <span class="text-gray-400">Categoria:</span>
                <span class="text-white">{{ product.category }}</span>
                <span v-if="product.sku" class="text-gray-400">SKU:</span>
                <span v-if="product.sku" class="text-white">{{ product.sku }}</span>
              </div>
            </div>

            <!-- Shipping Info -->
            <div class="bg-white/5 rounded-xl p-6 space-y-3 border border-white/10 hover:border-purple-500/30 transition-all">
              <h3 class="text-white font-semibold text-lg flex items-center gap-2">
                <span>🚚</span> Informacion de Envio
              </h3>
              <div class="flex items-center gap-3 text-gray-300 hover:text-white transition-colors">
                <span class="text-xl">📦</span>
                <span>Envio en 24-48 horas</span>
              </div>
              <div class="flex items-center gap-3 text-gray-300 hover:text-white transition-colors">
                <span class="text-xl">🎁</span>
                <span>Envio gratis en pedidos mayores a S/ 100</span>
              </div>
              <div class="flex items-center gap-3 text-gray-300 hover:text-white transition-colors">
                <span class="text-xl">🔄</span>
                <span>30 dias para cambios y devoluciones</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Reviews Section -->
        <div class="bg-white/10 backdrop-blur-md rounded-2xl p-8 mb-12 border border-white/20 hover:border-purple-500/30 transition-all animate-fade-in-up" style="animation-delay: 0.4s;">
          <h2 class="text-2xl font-bold text-white mb-6 flex items-center gap-2">
            <span>⭐</span> Reseñas del Producto
          </h2>
          
          <div v-if="reviews.length === 0" class="text-center py-8">
            <div class="text-5xl mb-4">💬</div>
            <p class="text-gray-400">No hay reseñas aun. Se el primero en opinar!</p>
          </div>

          <div v-else class="space-y-6">
            <div v-for="review in reviews" :key="review.id" class="border-b border-white/10 pb-6 hover:bg-white/5 p-4 rounded-xl transition-all">
              <div class="flex items-center justify-between mb-2">
                <div class="flex items-center gap-2">
                  <div class="w-10 h-10 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center text-white font-bold">
                    {{ (review.user?.name || review.user?.username || review.userId || 'U')[0].toUpperCase() }}
                  </div>
                  <span class="text-white font-semibold">{{ review.user?.name || review.user?.username || review.userId || 'Usuario' }}</span>
                  <span v-if="review.isVerified || review.purchaseVerified" class="text-green-400 text-sm flex items-center gap-1">✓ Verificado</span>
                </div>
                <div class="text-yellow-400 text-lg">
                  {{ '★'.repeat(review.rating || 5) }}{{ '☆'.repeat(5 - (review.rating || 5)) }}
                </div>
              </div>
              <h4 class="text-white font-medium mb-1">{{ review.title || 'Sin titulo' }}</h4>
              <p class="text-gray-300">{{ review.comment || 'Sin comentario' }}</p>
              <p class="text-gray-500 text-sm mt-2">{{ formatDate(review.createdAt) }}</p>
            </div>
            <div v-if="reviews.length === 0" class="text-center py-4">
              <p class="text-gray-400">No hay reseñas aún. ¡Sé el primero en opinar!</p>
            </div>
          </div>

          <!-- Add Review Form -->
          <div v-if="isLoggedIn && reviewsError === ''" class="mt-8 pt-6 border-t border-white/10">
            <h3 class="text-white font-semibold text-lg mb-4 flex items-center gap-2">
              <span>✍️</span> Escribir una Resena
            </h3>
            <div class="space-y-4">
              <div>
                <label class="text-gray-400 text-sm mb-1 block">Calificacion</label>
                <div class="flex gap-2">
                  <button 
                    v-for="star in 5" 
                    :key="star"
                    @click="newReview.rating = star"
                    class="text-3xl transition-transform hover:scale-125"
                    :class="star <= newReview.rating ? 'text-yellow-400' : 'text-gray-500'"
                  >
                    {{ star <= newReview.rating ? '★' : '☆' }}
                  </button>
                </div>
              </div>
              <div>
                <input 
                  v-model="newReview.title" 
                  placeholder="Titulo de tu resena"
                  class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all"
                />
              </div>
              <div>
                <textarea 
                  v-model="newReview.comment" 
                  placeholder="Escribe tu resena..."
                  rows="3"
                  class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all"
                ></textarea>
              </div>
              <button 
                @click="submitReview"
                class="px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-bold hover:from-purple-700 hover:to-pink-700 transform hover:scale-105 transition-all"
              >
                📤 Enviar Resena
              </button>
            </div>
          </div>
        </div>

        <!-- Related Products -->
        <div v-if="relatedProducts.length > 0" class="mb-12 animate-fade-in-up" style="animation-delay: 0.6s;">
          <h2 class="text-2xl font-bold text-white mb-6 flex items-center gap-2">
            <span>🔗</span> Productos Relacionados
          </h2>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div 
              v-for="related in relatedProducts" 
              :key="related.id"
              class="bg-white/10 backdrop-blur-md rounded-xl overflow-hidden border border-white/20 hover:shadow-2xl hover:border-purple-500/50 transition-all duration-300 hover:-translate-y-2 group"
            >
              <div class="h-48 bg-gradient-to-br from-purple-500/30 to-pink-500/30 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
                <span class="text-5xl transform group-hover:rotate-12 transition-transform duration-300">{{ getProductEmoji(related) }}</span>
              </div>
              <div class="p-4">
                <h3 class="text-white font-semibold mb-1 line-clamp-1 group-hover:text-purple-400 transition-colors">{{ related.name }}</h3>
                <p class="text-purple-400 font-bold">S/ {{ Number(related.price).toFixed(2) }}</p>
                <RouterLink 
                  :to="`/product/${related.id}`"
                  class="block mt-2 text-center py-2 bg-white/10 text-white rounded-lg text-sm hover:bg-purple-600 transition-all"
                >
                  Ver Detalle
                </RouterLink>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { productsAPI, reviewsAPI } from '../api'
import api from '../api'
import { useCartStore } from '../stores/cart'
import { useAuthStore } from '../stores/auth'
import type { Product, Review } from '../types'

const route = useRoute()
const router = useRouter()
const cartStore = useCartStore()
const authStore = useAuthStore()

const product = ref<Product | null>(null)
const loading = ref(true)
const quantity = ref(1)
const reviews = ref<Review[]>([])
const reviewsError = ref('')
const relatedProducts = ref<Product[]>([])
const isInWishlist = ref(false)

const newReview = ref({
  rating: 5,
  title: '',
  comment: ''
})

const isLoggedIn = computed(() => authStore.isAuthenticated)

const getProductEmoji = (p: any): string => {
  const category = (p?.category || '').toLowerCase()
  if (category.includes('hombre') || category.includes('men')) return String.fromCodePoint(0x1F455)
  if (category.includes('mujer') || category.includes('women')) return String.fromCodePoint(0x1F457)
  if (category.includes('shoes') || category.includes('zapato')) return String.fromCodePoint(0x1F45F)
  if (category.includes('accessories') || category.includes('accesorio')) return String.fromCodePoint(0x1F6C1)
  return String.fromCodePoint(0x1F455)
}

const formatDate = (dateStr: any): string => {
  if (!dateStr) return 'Hace poco'
  try {
    if (typeof dateStr === 'string' && dateStr.includes('-')) {
      const parts = dateStr.split('-')
      if (parts[0].length === 4) {
        const date = new Date(dateStr)
        if (isNaN(date.getTime())) return 'Hace poco'
        return date.toLocaleDateString('es-ES', { year: 'numeric', month: 'long', day: 'numeric' })
      }
    }
    const date = new Date(dateStr)
    if (isNaN(date.getTime())) return 'Hace poco'
    return date.toLocaleDateString('es-ES', { year: 'numeric', month: 'long', day: 'numeric' })
  } catch {
    return 'Hace poco'
  }
}

const addToCart = () => {
  if (product.value && product.value.stock > 0) {
    cartStore.addItem(product.value, quantity.value)
    router.push('/cart')
  }
}

const toggleWishlist = () => {
  if (!isLoggedIn.value) {
    router.push('/login')
    return
  }
  isInWishlist.value = !isInWishlist.value
}

const submitReview = async () => {
  if (!product.value || !newReview.value.title || !newReview.value.comment) return
  
  try {
    await reviewsAPI.create({
      productId: product.value.id,
      rating: newReview.value.rating,
      title: newReview.value.title,
      comment: newReview.value.comment
    })
    newReview.value = { rating: 5, title: '', comment: '' }
    loadReviews()
  } catch (err) {
    console.error('Error submitting review:', err)
  }
}

const loadReviews = async () => {
  if (!product.value) return
  reviewsError.value = ''
  try {
    const response = await api.get(`/reviews`, { params: { productId: product.value.id, limit: 50 } })
    console.log('API Response:', response.data)
    
    // API returns { reviews: [...], total, pages, averageRating, ... }
    let reviewsData = []
    if (response.data?.reviews) {
      reviewsData = response.data.reviews
    } else if (response.data?.data) {
      reviewsData = response.data.data
    } else if (Array.isArray(response.data)) {
      reviewsData = response.data
    }
    
    reviews.value = reviewsData
    console.log('Final reviews:', reviews.value)
  } catch (err: any) {
    console.error('Error loading reviews:', err)
    reviewsError.value = err.response?.status === 404 ? '' : 'No se pudieron cargar las reseñas'
    reviews.value = []
  }
}

const loadRelatedProducts = async () => {
  if (!product.value || !product.value.category) return
  try {
    const response = await productsAPI.getByCategory(product.value.category)
    if (response.data && Array.isArray(response.data)) {
      relatedProducts.value = response.data.filter((p: Product) => p.id !== product.value?.id).slice(0, 4)
    } else {
      relatedProducts.value = []
    }
  } catch (err) {
    console.error('Error loading related products:', err)
    relatedProducts.value = []
  }
}

onMounted(async () => {
  try {
    const idParam = route.params.id as string
    const id = parseInt(idParam)
    if (isNaN(id)) {
      console.error('Invalid product ID:', idParam)
      loading.value = false
      return
    }
    const response = await productsAPI.getById(id)
    product.value = response.data
    
    await Promise.all([loadReviews(), loadRelatedProducts()])
  } catch (err) {
    console.error(err)
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-fade-in-up {
  animation: fadeInUp 0.6s ease-out forwards;
  opacity: 0;
}

@keyframes scaleIn {
  from {
    opacity: 0;
    transform: scale(0.9);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

.animate-scale-in {
  animation: scaleIn 0.6s ease-out forwards;
}
</style>
