// tienda-frontend/src/pages/OrderDetail.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { adminApi } from '../services/adminApi';

interface OrderItem {
  id: number;
  quantity: number;
  price: number;
  product: {
    id: number;
    name: string;
    imageUrl?: string;
  };
}

interface Order {
  id: number;
  orderNumber: string;
  status: string;
  total: number;
  createdAt: string;
  updatedAt: string;
  shippingAddress: string;
  trackingCode?: string;
  estimatedDeliveryDate?: string;
  user: {
    id: number;
    username: string;
    email: string;
  };
  items: OrderItem[];
  statusHistory?: Array<{
    id: number;
    status: string;
    createdAt: string;
    notes?: string;
  }>;
}

const OrderDetail: React.FC = () => {
  const { orderId } = useParams<{ orderId: string }>();
  const navigate = useNavigate();
  const [order, setOrder] = useState<Order | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (orderId) {
      fetchOrderDetail(parseInt(orderId));
    }
  }, [orderId]);

  const fetchOrderDetail = async (id: number) => {
    try {
      setLoading(true);
      const orderData = await adminApi.getOrderById(id);
      setOrder(orderData);
    } catch (err: any) {
      setError(err.message || 'Error al cargar los detalles de la orden');
      console.error('Error fetching order detail:', err);
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status: string) => {
    const colors = {
      pending: 'bg-yellow-500/30 text-yellow-100 border border-yellow-400/50',
      processing: 'bg-blue-500/30 text-blue-100 border border-blue-400/50',
      shipped: 'bg-purple-500/30 text-purple-100 border border-purple-400/50',
      delivered: 'bg-green-500/30 text-green-100 border border-green-400/50',
      cancelled: 'bg-red-500/30 text-red-100 border border-red-400/50',
    };
    return colors[status as keyof typeof colors] || 'bg-gray-500/30 text-gray-100 border border-gray-400/50';
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'pending':
        return 'Pendiente';
      case 'processing':
        return 'Procesando';
      case 'shipped':
        return 'Enviado';
      case 'delivered':
        return 'Entregado';
      case 'cancelled':
        return 'Cancelado';
      default:
        return status;
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center relative overflow-hidden">
        {/* Floating Orbs */}
        <div className="fixed inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
        </div>
        <div className="text-center relative z-10">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-purple-400 mx-auto mb-4"></div>
          <p className="text-gray-300 text-lg">⏳ Cargando detalles de la orden...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center relative overflow-hidden">
        {/* Floating Orbs */}
        <div className="fixed inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
        </div>
        <div className="text-center relative z-10">
          <div className="text-red-400 text-6xl mb-4">❌</div>
          <h2 className="text-3xl font-bold text-white mb-2">Error</h2>
          <p className="text-gray-300 mb-8 text-lg">{error}</p>
          <button
            onClick={() => navigate('/profile')}
            className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-8 py-4 rounded-full font-bold text-lg hover:from-purple-700 hover:to-pink-700 transition-all duration-300 shadow-lg"
          >
            ⬅️ Volver al Perfil
          </button>
        </div>
      </div>
    );
  }

  if (!order) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center relative overflow-hidden">
        {/* Floating Orbs */}
        <div className="fixed inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
        </div>
        <div className="text-center relative z-10">
          <div className="text-yellow-400 text-6xl mb-4">📦</div>
          <h2 className="text-3xl font-bold text-white mb-2">Orden no encontrada</h2>
          <p className="text-gray-300 mb-8 text-lg">La orden solicitada no existe o no tienes permisos para verla.</p>
          <button
            onClick={() => navigate('/profile')}
            className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-8 py-4 rounded-full font-bold text-lg hover:from-purple-700 hover:to-pink-700 transition-all duration-300 shadow-lg"
          >
            ⬅️ Volver al Perfil
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 py-12 relative overflow-hidden">
      {/* Floating Gradient Orbs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
      </div>

      <div className="container mx-auto px-4 max-w-4xl relative z-10">
        {/* Header */}
        <div className="mb-8">
          <button
            onClick={() => navigate('/profile')}
            className="flex items-center text-gray-300 hover:text-white mb-6 font-semibold text-lg group"
          >
            <span className="group-hover:-translate-x-2 transition-transform">⬅️</span>
            <span className="ml-2">Volver al Perfil</span>
          </button>
          <h1 className="text-5xl font-bold text-white">
            📋 Detalles de la Orden #{order.orderNumber}
          </h1>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Order Information */}
          <div className="lg:col-span-2">
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl shadow-2xl p-8 mb-8 hover:border-white/30 transition-all duration-300">
              <h2 className="text-2xl font-bold text-white mb-6">ℹ️ Información de la Orden</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-white/5 border border-white/10 rounded-2xl p-4">
                  <p className="text-gray-400 text-sm font-medium mb-1">Número de Orden</p>
                  <p className="text-white font-bold text-lg">{order.orderNumber}</p>
                </div>
                <div className="bg-white/5 border border-white/10 rounded-2xl p-4">
                  <p className="text-gray-400 text-sm font-medium mb-2">Estado</p>
                  <span className={`inline-block px-4 py-2 rounded-full text-sm font-bold backdrop-blur-sm ${getStatusColor(order.status)}`}>
                    {getStatusText(order.status)}
                  </span>
                </div>
                <div className="bg-white/5 border border-white/10 rounded-2xl p-4">
                  <p className="text-gray-400 text-sm font-medium mb-1">📅 Fecha de Creación</p>
                  <p className="text-white font-semibold">{formatDate(order.createdAt)}</p>
                </div>
                <div className="bg-white/5 border border-white/10 rounded-2xl p-4">
                  <p className="text-gray-400 text-sm font-medium mb-1">Total</p>
                  <p className="text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text font-bold text-lg">
                    ${typeof order.total === 'number' ? order.total.toFixed(2) : parseFloat(order.total || '0').toFixed(2)}
                  </p>
                </div>
              </div>
            </div>

            {/* Order Items */}
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl shadow-2xl p-8 mb-8 hover:border-white/30 transition-all duration-300">
              <h2 className="text-2xl font-bold text-white mb-6">🛍️ Productos</h2>
              <div className="space-y-4">
                {order.items.map((item) => (
                  <div key={item.id} className="flex items-center gap-4 p-4 bg-white/5 border border-white/10 rounded-2xl hover:bg-white/10 transition-all duration-300">
                    <img
                      src={item.product.imageUrl || 'https://via.placeholder.com/80x80'}
                      alt={item.product.name}
                      className="w-20 h-20 object-cover rounded-xl ring-2 ring-white/20"
                    />
                    <div className="flex-1">
                      <h3 className="font-bold text-white text-lg">{item.product.name}</h3>
                      <p className="text-gray-300 text-sm">📦 Cantidad: {item.quantity}</p>
                      <p className="text-gray-400 text-sm">
                        💵 Precio unitario: ${typeof item.price === 'number' ? item.price.toFixed(2) : parseFloat(item.price || '0').toFixed(2)}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text font-bold text-lg">
                        ${(typeof item.price === 'number' ? item.price * item.quantity : parseFloat(item.price || '0') * item.quantity).toFixed(2)}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Shipping Address */}
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl shadow-2xl p-8 hover:border-white/30 transition-all duration-300">
              <h2 className="text-2xl font-bold text-white mb-6">🚚 Dirección de Envío</h2>
              <p className="text-gray-300 text-lg leading-relaxed bg-white/5 border border-white/10 rounded-2xl p-4">{order.shippingAddress}</p>
            </div>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1">
            {/* Tracking Information */}
            {order.trackingCode && (
              <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl shadow-2xl p-8 mb-8 hover:border-white/30 transition-all duration-300">
                <h2 className="text-xl font-bold text-white mb-6">📍 Seguimiento</h2>
                <div className="bg-white/5 border border-white/10 rounded-2xl p-4 mb-4">
                  <p className="text-gray-400 text-sm font-medium mb-1">Código de Seguimiento</p>
                  <p className="text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text font-mono font-bold break-all">{order.trackingCode}</p>
                </div>
                {order.estimatedDeliveryDate && (
                  <div className="bg-white/5 border border-white/10 rounded-2xl p-4">
                    <p className="text-gray-400 text-sm font-medium mb-1">📅 Fecha Estimada</p>
                    <p className="text-white font-semibold">{formatDate(order.estimatedDeliveryDate)}</p>
                  </div>
                )}
              </div>
            )}

            {/* Status History */}
            {order.statusHistory && order.statusHistory.length > 0 && (
              <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl shadow-2xl p-8 hover:border-white/30 transition-all duration-300">
                <h2 className="text-xl font-bold text-white mb-6">📈 Historial de Estados</h2>
                <div className="space-y-4">
                  {order.statusHistory
                    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
                    .map((history) => (
                      <div key={history.id} className="flex items-start gap-3 bg-white/5 border border-white/10 rounded-2xl p-3">
                        <div className="w-3 h-3 bg-gradient-to-r from-purple-400 to-pink-400 rounded-full mt-2 flex-shrink-0 shadow-lg"></div>
                        <div className="flex-1">
                          <p className="font-bold text-white text-sm">{getStatusText(history.status)}</p>
                          <p className="text-gray-400 text-xs">{formatDate(history.createdAt)}</p>
                          {history.notes && (
                            <p className="text-gray-300 text-sm mt-1">{history.notes}</p>
                          )}
                        </div>
                      </div>
                    ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default OrderDetail;

// tienda-frontend/src/pages/OrderDetail.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 py-16 px-4">
    <div class="fixed inset-0 overflow-hidden pointer-events-none">
      <div class="absolute -top-40 -right-40 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl"></div>
      <div class="absolute -bottom-40 -left-40 w-96 h-96 bg-pink-500/10 rounded-full blur-3xl"></div>
    </div>

    <div v-if="loading" class="max-w-4xl mx-auto relative z-10">
      <div class="animate-pulse space-y-8">
        <div class="bg-white/10 rounded-2xl p-8">
          <div class="h-8 bg-white/20 rounded w-1/3 mb-6"></div>
          <div class="grid grid-cols-4 gap-4">
            <div v-for="i in 4" :key="i" class="h-12 bg-white/10 rounded"></div>
          </div>
        </div>
      </div>
    </div>

    <div v-else-if="!order" class="max-w-4xl mx-auto text-center py-20 animate-fade-in-up relative z-10">
      <Card class="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl p-12 max-w-lg mx-auto">
        <div class="text-8xl mb-6">😕</div>
        <h2 class="text-3xl font-bold text-white mb-4">Pedido no encontrado</h2>
        <p class="text-gray-300 mb-8">El pedido que buscas no existe o no tienes acceso.</p>
        <RouterLink to="/orders">
          <Button class="transform hover:scale-105 shadow-xl">← Ver Mis Pedidos</Button>
        </RouterLink>
      </Card>
    </div>

    <div v-else class="max-w-4xl mx-auto relative z-10">
      <div class="mb-6 animate-fade-in-up">
        <RouterLink to="/orders" class="text-purple-400 hover:text-purple-300 hover:underline transition-colors inline-flex items-center gap-2">
          ← Volver a pedidos
        </RouterLink>
      </div>

      <div class="bg-gradient-to-br from-gray-800 to-gray-900 rounded-3xl p-8 shadow-2xl border border-gray-700/50 animate-fade-in-up" style="animation-delay: 0.1s;">
        <div class="flex items-center justify-between mb-6 flex-wrap gap-4">
          <div>
            <h1 class="text-3xl font-bold text-white mb-2">Pedido #{{ order.orderNumber }}</h1>
            <p class="text-gray-400">{{ formatDate(order.createdAt) }}</p>
          </div>
          <Badge :class="getStatusClass(order.status)" class="text-lg px-4 py-2">
            {{ getStatusDisplayName(order.status) }}
          </Badge>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div class="bg-gray-800/50 rounded-xl p-6 text-center border border-gray-700/50">
            <p class="text-gray-400 text-sm mb-1">Total</p>
            <p class="text-3xl font-bold text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text">
              S/ {{ Number(order.total).toFixed(2) }}
            </p>
          </div>
          <div class="bg-gray-800/50 rounded-xl p-6 text-center border border-gray-700/50">
            <p class="text-gray-400 text-sm mb-1">Estado</p>
            <p class="text-2xl font-bold text-white">{{ getStatusDisplayName(order.status) }}</p>
          </div>
          <div class="bg-gray-800/50 rounded-xl p-6 text-center border border-gray-700/50">
            <p class="text-gray-400 text-sm mb-1">Artículos</p>
            <p class="text-2xl font-bold text-white">{{ order.items?.length || 0 }}</p>
          </div>
        </div>

        <div class="border-t border-gray-700/50 mb-6 pt-6">
          <h2 class="text-2xl font-bold text-white mb-4">📦 Detalles del Envío</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div v-if="order.shippingAddress" class="bg-gray-800/50 rounded-xl p-6 border border-gray-700/50">
              <h3 class="text-white font-semibold mb-3 flex items-center gap-2">📍 Dirección de Envío</h3>
              <p class="text-gray-300 whitespace-pre-line">{{ order.shippingAddress }}</p>
            </div>
            <div v-if="order.billingAddress" class="bg-gray-800/50 rounded-xl p-6 border border-gray-700/50">
              <h3 class="text-white font-semibold mb-3 flex items-center gap-2">💳 Dirección de Facturación</h3>
              <p class="text-gray-300 whitespace-pre-line">{{ order.billingAddress }}</p>
            </div>
          </div>
        </div>

        <div v-if="order.trackingCode" class="bg-gradient-to-r from-blue-600/30 to-indigo-600/30 border border-blue-400/50 rounded-2xl p-6 mb-6">
          <h3 class="text-white font-semibold text-lg mb-4 flex items-center gap-2">📍 Rastreo</h3>
          <div class="flex items-center gap-4 flex-wrap">
            <p class="text-blue-300"><strong>Código:</strong> {{ order.trackingCode }}</p>
            <p v-if="order.shippingCarrier" class="text-blue-300"><strong>Transportista:</strong> {{ order.shippingCarrier }}</p>
            <RouterLink v-if="order.trackingCode" :to="`/order-tracking/${order.id}`" class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-all text-sm">
              📍 Rastrear Envío
            </RouterLink>
          </div>
        </div>

        <h2 class="text-2xl font-bold text-white mb-4">🛍️ Artículos del Pedido</h2>
        <div class="space-y-4">
          <div v-for="item in order.items" :key="item.id" class="bg-gray-800/50 rounded-xl p-4 border border-gray-700/50 flex flex-col md:flex-row items-center md:items-start gap-4">
            <div class="w-20 h-20 rounded-lg bg-gradient-to-br from-purple-500/30 to-pink-500/30 flex items-center justify-center flex-shrink-0 overflow-hidden">
              <img
                :src="getProductImage(item.product?.name || item.name || '', item.product?.category || '', item.product?.imageUrl)"
                :alt="item.product?.name || item.name || `Producto #${item.productId}`"
                class="w-full h-full object-cover"
              />
            </div>
            <div class="flex-1">
              <h4 class="font-bold text-white">{{ item.product?.name || item.name || `Producto #${item.productId}` }}</h4>
              <p class="text-gray-400 text-sm">Cantidad: {{ item.quantity }} × S/ {{ Number(item.price).toFixed(2) }}</p>
            </div>
            <div class="text-right">
              <p class="text-white font-bold text-lg">S/ {{ (Number(item.price) * item.quantity).toFixed(2) }}</p>
            </div>
          </div>
        </div>

        <div class="mt-8 border-t border-gray-700/50 pt-6">
          <h2 class="text-xl font-bold text-white mb-4">💰 Resumen de Pagos</h2>
          <div class="space-y-3">
            <div class="flex justify-between text-gray-300">
              <span>Subtotal</span>
              <span>S/ {{ (Number(order.total) / 1.15).toFixed(2) }}</span>
            </div>
            <div class="flex justify-between text-gray-300">
              <span>Impuestos (15%)</span>
              <span>S/ {{ (Number(order.total) * 0.15 / 1.15).toFixed(2) }}</span>
            </div>
            <div class="flex justify-between text-gray-300">
              <span>Envío</span>
              <Badge variant="success" icon="🚚">GRATIS</Badge>
            </div>
            <div class="flex justify-between text-xl font-bold text-white pt-3 border-t border-gray-700/50">
              <span>Total Pagado</span>
              <span class="text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text">S/ {{ Number(order.total).toFixed(2) }}</span>
            </div>
          </div>
        </div>

        <div v-if="order.status === 'delivered' && order.actualDeliveryDate" class="mt-6 p-4 bg-green-500/20 border border-green-400/30 rounded-xl">
          <p class="text-green-300 text-center">
            ✅ Entregado el {{ formatDate(order.actualDeliveryDate) }}
          </p>
        </div>

        <div v-if="order.status === 'cancelled'" class="mt-6 p-4 bg-red-500/20 border border-red-400/30 rounded-xl">
          <p class="text-red-300 text-center">
            ❌ Pedido cancelado: {{ order.cancellationReason || 'Sin razón especificada' }}
          </p>
        </div>
      </div>

      <div class="mt-6 text-center animate-fade-in-up" style="animation-delay: 0.3s;">
        <RouterLink to="/orders" class="px-6 py-3 bg-gray-800 border border-gray-700 text-white rounded-xl hover:bg-gray-700 transition-all font-semibold">
          ← Volver a Mis Pedidos
        </RouterLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ordersAPI } from '../api'
import type { Order } from '../types'
import { Card, Badge, RouterLink } from '../components/ui'
import { getProductImage } from '../utils/productImages'

const route = useRoute()
const router = useRouter()

const order = ref<Order | null>(null)
const loading = ref(true)

const formatDate = (dateStr: string) => {
  if (!dateStr) return 'N/A'
  try {
    return new Date(dateStr).toLocaleDateString('es-ES', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch {
    return dateStr
  }
}

const getStatusClass = (status: string) => {
  const classes: Record<string, string> = {
    delivered: 'bg-green-500/20 text-green-300 border border-green-400/30',
    shipped: 'bg-purple-500/20 text-purple-300 border border-purple-400/30',
    processing: 'bg-yellow-500/20 text-yellow-300 border border-yellow-400/30',
    pending: 'bg-gray-500/20 text-gray-300 border border-gray-400/30',
    cancelled: 'bg-red-500/20 text-red-300 border border-red-400/30',
  }
  return classes[status] || 'bg-gray-500/20 text-gray-300 border border-gray-400/30'
}

const getStatusDisplayName = (status: string) => {
  const names: Record<string, string> = {
    delivered: 'Entregado',
    shipped: 'Enviado',
    processing: 'Procesando',
    pending: 'Pendiente',
    cancelled: 'Cancelado',
  }
  return names[status] || status
}

onMounted(async () => {
  try {
    const idParam = route.params.orderId as string
    const id = parseInt(idParam)
    if (isNaN(id)) {
      router.push('/orders')
      return
    }
    const response = await ordersAPI.getById(id)
    order.value = response.data
  } catch (err) {
    console.error(err)
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
@keyframes fadeInUp {
  from { opacity: 0; transform: translateY(30px); }
  to { opacity: 1; transform: translateY(0); }
}
.animate-fade-in-up { animation: fadeInUp 0.6s ease-out forwards; opacity: 0; }
</style>
