// tienda-frontend/src/pages/Products.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { productsAPI } from '../services/api';
import ProductCard from '../components/ProductCard';
import ProductQuickView from '../components/ProductQuickView';

const Products: React.FC = () => {
  const navigate = useNavigate();
  const [products, setProducts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [sortBy, setSortBy] = useState('name');
  const [quickViewProduct, setQuickViewProduct] = useState<any>(null);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [showFilters, setShowFilters] = useState(false);
  const [comparisonItems, setComparisonItems] = useState<any[]>([]);
  const [showComparison, setShowComparison] = useState(false);
  const [filters, setFilters] = useState({
    category: '',
    brand: '',
    priceRange: [0, 1000] as [number, number],
    colors: [] as string[],
    sizes: [] as string[],
    rating: 0,
    inStock: true,
    onSale: false,
    featured: false,
    new: false,
    bestseller: false,
  });

  // Filter options for the ProductFilters component (unused for now)
  // const filterOptions = {
  //   categories: ['dresses', 'shirts', 'pants', 'jackets', 'skirts', 'sweaters'],
  //   brands: ['Elegance', 'Casual Co', 'Denim Pro', 'Leather Works', 'Nike', 'Adidas', 'Zara', 'H&M'],
  //   colors: ['Negro', 'Blanco', 'Azul', 'Rojo', 'Verde', 'Gris', 'Marrón', 'Rosa'],
  //   sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '28', '30', '32', '34', '36'],
  //   priceRange: [0, 1000] as [number, number],
  // };

  // Mock data fallback
  const mockProducts = [
    {
      id: 1,
      name: "Vestido Elegante Negro",
      description: "Vestido negro elegante perfecto para ocasiones especiales y eventos formales",
      price: 89.99,
      stock: 15,
      imageUrl: "https://images.unsplash.com/photo-1566479179817-05b6f6baefb8?w=400&h=500&fit=crop",
      category: "dresses",
      brand: "Elegance",
      colors: ["Negro"],
      sizes: ["S", "M", "L", "XL"],
      rating: 4.5,
      isNew: true,
      isFeatured: false,
      isOnSale: false,
      isBestseller: false
    },
    {
      id: 2,
      name: "Camisa Casual Blanca",
      description: "Camisa de algodón cómoda y fresca para el día a día",
      price: 45.50,
      stock: 25,
      imageUrl: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400&h=500&fit=crop",
      category: "shirts",
      brand: "Casual Co",
      colors: ["Blanco"],
      sizes: ["XS", "S", "M", "L", "XL"],
      rating: 4.2,
      isNew: false,
      isFeatured: true,
      isOnSale: true,
      isBestseller: true
    },
    {
      id: 3,
      name: "Jeans Premium Azul",
      description: "Jeans de alta calidad con corte moderno y cómodo",
      price: 79.99,
      stock: 20,
      imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=500&fit=crop",
      category: "pants",
      brand: "Denim Pro",
      colors: ["Azul"],
      sizes: ["28", "30", "32", "34", "36"],
      rating: 4.7,
      isNew: false,
      isFeatured: false,
      isOnSale: false,
      isBestseller: true
    },
    {
      id: 4,
      name: "Chaqueta de Cuero",
      description: "Chaqueta de cuero genuino estilo motociclista",
      price: 199.99,
      stock: 8,
      imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop",
      category: "jackets",
      brand: "Leather Works",
      colors: ["Negro", "Marrón"],
      sizes: ["S", "M", "L", "XL"],
      rating: 4.8,
      isNew: true,
      isFeatured: true,
      isOnSale: false,
      isBestseller: false
    }
  ];

  // Fetch products from API
  const fetchProducts = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await productsAPI.getAll();
      
      if (response?.data && Array.isArray(response.data)) {
        // Clean and process API data
        const cleanedProducts = response.data
          .filter(product => product && product.id && product.name)
          .map(product => ({
            ...product,
            imageUrl: product.imageUrl || product.image || "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=500&fit=crop",
            price: parseFloat(product.price) || 0,
            stock: parseInt(product.stock) || 0,
            rating: product.rating || 0,
            isNew: product.isNew || false,
            isFeatured: product.isFeatured || false,
            isOnSale: product.isOnSale || false,
            isBestseller: product.isBestseller || false,
            colors: product.colors || [],
            sizes: product.sizes || [],
            brand: product.brand || 'Sin marca'
          }));
        
        setProducts(cleanedProducts);
      } else {
        console.warn('API response invalid, using mock data');
        setProducts(mockProducts);
      }
    } catch (error) {
      console.error('Error fetching products:', error);
      setError('Error al cargar productos. Mostrando datos de ejemplo.');
      setProducts(mockProducts);
    } finally {
      setLoading(false);
    }
  };

  // Filter and search products using useMemo for better performance
  const filteredProducts = useMemo(() => {
    let filtered = [...products];

    // Search filter
    if (searchTerm) {
      filtered = filtered.filter(product =>
        product.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        product.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
        product.brand.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    // Category filter
    if (filters.category) {
      filtered = filtered.filter(product => product.category === filters.category);
    }

    // Brand filter
    if (filters.brand) {
      filtered = filtered.filter(product => product.brand === filters.brand);
    }

    // Price range filter
    filtered = filtered.filter(product => 
      product.price >= filters.priceRange[0] && product.price <= filters.priceRange[1]
    );

    // Colors filter
    if (filters.colors.length > 0) {
      filtered = filtered.filter(product =>
        product.colors?.some((color: string) => filters.colors.includes(color))
      );
    }

    // Sizes filter
    if (filters.sizes.length > 0) {
      filtered = filtered.filter(product =>
        product.sizes?.some((size: string) => filters.sizes.includes(size))
      );
    }

    // Rating filter
    if (filters.rating > 0) {
      filtered = filtered.filter(product => product.rating >= filters.rating);
    }

    // Stock filter
    if (filters.inStock) {
      filtered = filtered.filter(product => product.stock > 0);
    }

    // Special filters
    if (filters.onSale) {
      filtered = filtered.filter(product => product.isOnSale);
    }
    if (filters.featured) {
      filtered = filtered.filter(product => product.isFeatured);
    }
    if (filters.new) {
      filtered = filtered.filter(product => product.isNew);
    }
    if (filters.bestseller) {
      filtered = filtered.filter(product => product.isBestseller);
    }

    // Apply sorting
    filtered.sort((a, b) => {
      switch (sortBy) {
        case 'price-low':
          return a.price - b.price;
        case 'price-high':
          return b.price - a.price;
        case 'rating':
          return b.rating - a.rating;
        case 'newest':
          return new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime();
        default:
          return a.name.localeCompare(b.name);
      }
    });

    return filtered;
  }, [products, searchTerm, filters, sortBy]);

  useEffect(() => {
    fetchProducts();
  }, []);

  // const handleFiltersChange = (newFilters: any) => {
  //   setFilters(newFilters);
  // };

  const clearFilters = () => {
    setFilters({
      category: '',
      brand: '',
      priceRange: [0, 1000],
      colors: [],
      sizes: [],
      rating: 0,
      inStock: true,
      onSale: false,
      featured: false,
      new: false,
      bestseller: false,
    });
    setSearchTerm('');
  };

  const handleAddToComparison = (product: any) => {
    if (comparisonItems.length < 3 && !comparisonItems.find(item => item.id === product.id)) {
      setComparisonItems([...comparisonItems, product]);
    }
  };

  const handleRemoveFromComparison = (productId: number) => {
    setComparisonItems(comparisonItems.filter(item => item.id !== productId));
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-purple-50 to-pink-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-purple-600 mx-auto mb-4"></div>
          <p className="text-gray-600 text-lg">Cargando productos...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-pink-50">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-800 mb-4">
            🛍️ Nuestros Productos
          </h1>
          <p className="text-gray-600 text-lg">
            Descubre nuestra colección de moda exclusiva
          </p>
        </div>

        {error && (
          <div className="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mb-6 rounded">
            <p className="font-medium">⚠️ {error}</p>
          </div>
        )}

        {/* Search and Controls */}
        <div className="mb-8 space-y-4">
          <div className="flex flex-col lg:flex-row gap-4 items-center justify-between">
            {/* Search Bar */}
            <div className="relative flex-1 max-w-md">
              <input
                type="text"
                placeholder="Buscar productos..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-full focus:ring-2 focus:ring-purple-500 focus:border-transparent"
              />
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <span className="text-gray-400">🔍</span>
              </div>
            </div>

            {/* Controls */}
            <div className="flex gap-4 items-center">
              {/* Sort */}
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
              >
                <option value="name">Nombre A-Z</option>
                <option value="price-low">Precio: Menor a Mayor</option>
                <option value="price-high">Precio: Mayor a Menor</option>
                <option value="rating">Mejor Calificados</option>
                <option value="newest">Más Nuevos</option>
              </select>

              {/* View Mode */}
              <div className="flex border border-gray-300 rounded-lg overflow-hidden">
                <button
                  onClick={() => setViewMode('grid')}
                  className={`px-3 py-2 ${viewMode === 'grid' ? 'bg-purple-600 text-white' : 'bg-white text-gray-600'}`}
                >
                  ⊞
                </button>
                <button
                  onClick={() => setViewMode('list')}
                  className={`px-3 py-2 ${viewMode === 'list' ? 'bg-purple-600 text-white' : 'bg-white text-gray-600'}`}
                >
                  ☰
                </button>
              </div>

              {/* Filters Toggle */}
              <button
                onClick={() => setShowFilters(!showFilters)}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
              >
                🎛️ Filtros
              </button>
            </div>
          </div>
        </div>

        <div className="flex gap-8">
          {/* Filters Sidebar */}
          {showFilters && (
            <div className="w-80 flex-shrink-0">
              {/* TODO: Implementar ProductFilters component */}
              <div className="bg-white p-6 rounded-lg shadow-md">
                <h3 className="text-lg font-semibold mb-4">Filtros</h3>
                <p className="text-gray-500">Filtros en desarrollo...</p>
              </div>
            </div>
          )}

          {/* Products Grid/List */}
          <div className="flex-1">
            {/* Results Count */}
            <div className="mb-6">
              <p className="text-gray-600">
                Mostrando <span className="font-bold text-purple-600">{filteredProducts.length}</span> productos
                {searchTerm && (
                  <span> para "<span className="font-bold">{searchTerm}</span>"
                  </span>
                )}
              </p>
            </div>

            {/* Products */}
            {filteredProducts.length > 0 ? (
              <div className={viewMode === 'grid' 
                ? "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
                : "space-y-4"
              }>
                {filteredProducts.map((product: any) => (
                  <ProductCard
                    key={product.id}
                    product={product}
                    onQuickView={() => setQuickViewProduct(product)}
                    onAddToComparison={() => handleAddToComparison(product)}
                    isInComparison={comparisonItems.some(item => item.id === product.id)}
                    viewMode={viewMode}
                  />
                ))}
              </div>
            ) : (
              <div className="text-center py-16">
                <div className="text-6xl mb-4">😢</div>
                <h3 className="text-2xl font-bold text-gray-800 mb-2">
                  No se encontraron productos
                </h3>
                <p className="text-gray-600 mb-6">
                  Intenta cambiar los filtros o el término de búsqueda
                </p>
                <button
                  onClick={clearFilters}
                  className="bg-purple-600 text-white px-8 py-3 rounded-full font-semibold hover:bg-purple-700 transition-colors"
                >
                  🔄 Limpiar Filtros
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Comparison Bar */}
        {comparisonItems.length > 0 && (
          <div className="fixed bottom-0 left-0 right-0 bg-white border-t shadow-lg p-4 z-40">
            <div className="container mx-auto flex items-center justify-between">
              <div className="flex items-center gap-4">
                <span className="font-semibold">Comparar productos ({comparisonItems.length}/3):</span>
                <div className="flex gap-2">
                  {comparisonItems.map(item => (
                    <div key={item.id} className="flex items-center bg-purple-100 px-3 py-1 rounded-full">
                      <span className="text-sm">{item.name}</span>
                      <button
                        onClick={() => handleRemoveFromComparison(item.id)}
                        className="ml-2 text-purple-600 hover:text-purple-800"
                      >
                        ×
                      </button>
                    </div>
                  ))}
                </div>
              </div>
              <button
                className="bg-purple-600 text-white px-6 py-2 rounded-lg hover:bg-purple-700 transition-colors"
                onClick={() => {
                  // Mostrar modal de comparación
                  setShowComparison(true);
                }}
              >
                Comparar
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Quick View Modal */}
      {quickViewProduct && (
        <ProductQuickView
          product={quickViewProduct}
          onClose={() => setQuickViewProduct(null)}
        />
      )}

      {/* Comparison Modal */}
      {showComparison && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl max-w-6xl w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-2xl font-bold text-gray-800">
                  Comparar Productos ({comparisonItems.length})
                </h2>
                <button
                  onClick={() => setShowComparison(false)}
                  className="text-gray-400 hover:text-gray-600 text-2xl"
                >
                  ✕
                </button>
              </div>

              {comparisonItems.length === 0 ? (
                <div className="text-center py-12">
                  <div className="text-6xl mb-4">⚖️</div>
                  <h3 className="text-xl font-bold text-gray-800 mb-2">No hay productos para comparar</h3>
                  <p className="text-gray-600">Agrega productos usando el botón de comparación</p>
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b">
                        <th className="text-left p-4 font-semibold">Característica</th>
                        {comparisonItems.map((product) => (
                          <th key={product.id} className="text-center p-4 min-w-[200px]">
                            <img
                              src={product.imageUrl}
                              alt={product.name}
                              className="w-20 h-20 object-cover rounded-lg mx-auto mb-2"
                            />
                            <h4 className="font-semibold text-sm">{product.name}</h4>
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      <tr className="border-b">
                        <td className="p-4 font-medium">Precio</td>
                        {comparisonItems.map((product) => (
                          <td key={product.id} className="text-center p-4">
                            <span className="text-xl font-bold text-purple-600">${product.price}</span>
                          </td>
                        ))}
                      </tr>
                      <tr className="border-b">
                        <td className="p-4 font-medium">Marca</td>
                        {comparisonItems.map((product) => (
                          <td key={product.id} className="text-center p-4">{product.brand || 'N/A'}</td>
                        ))}
                      </tr>
                      <tr className="border-b">
                        <td className="p-4 font-medium">Categoría</td>
                        {comparisonItems.map((product) => (
                          <td key={product.id} className="text-center p-4">{product.category}</td>
                        ))}
                      </tr>
                      <tr className="border-b">
                        <td className="p-4 font-medium">Stock</td>
                        {comparisonItems.map((product) => (
                          <td key={product.id} className="text-center p-4">
                            <span className={product.stock > 0 ? 'text-green-600' : 'text-red-600'}>
                              {product.stock > 0 ? `${product.stock} disponibles` : 'Sin stock'}
                            </span>
                          </td>
                        ))}
                      </tr>
                      <tr className="border-b">
                        <td className="p-4 font-medium">Calificación</td>
                        {comparisonItems.map((product) => (
                          <td key={product.id} className="text-center p-4">
                            <div className="flex justify-center items-center gap-1">
                              <span className="text-yellow-400">★</span>
                              <span>{product.rating || 'N/A'}</span>
                            </div>
                          </td>
                        ))}
                      </tr>
                      <tr>
                        <td className="p-4 font-medium">Acciones</td>
                        {comparisonItems.map((product) => (
                          <td key={product.id} className="text-center p-4">
                            <div className="flex flex-col gap-2">
                              <button
                                onClick={() => navigate(`/product/${product.id}`)}
                                className="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 transition-colors text-sm"
                              >
                                Ver Detalles
                              </button>
                              <button
                                onClick={() => handleRemoveFromComparison(product.id)}
                                className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm"
                              >
                                Quitar
                              </button>
                            </div>
                          </td>
                        ))}
                      </tr>
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Products;

// tienda-frontend/src/pages/Products.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 py-8">
    <div class="fixed inset-0 overflow-hidden pointer-events-none">
      <div class="absolute top-20 -right-20 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl"></div>
      <div class="absolute bottom-20 -left-20 w-64 h-64 bg-pink-500/10 rounded-full blur-3xl"></div>
    </div>

    <div class="max-w-7xl mx-auto px-4 relative z-10">
      <div class="mb-8 animate-fade-in-up">
        <h1 class="text-4xl md:text-5xl font-black text-white mb-4">
          Todos los <span class="text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text">Productos</span>
        </h1>
        <p class="text-gray-400 text-lg">Descubre nuestra colección completa</p>
        
        <div class="flex flex-col md:flex-row gap-4 justify-between items-center mt-6">
          <div class="relative flex-1 max-w-md group">
            <input
              v-model="searchTerm"
              type="text"
              placeholder="Buscar productos, marcas, categorías..."
              class="w-full pl-12 pr-12 py-3 bg-white/10 border border-white/20 rounded-full text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all group-hover:bg-white/15"
            />
            <span class="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 group-hover:scale-110 transition-transform">🔍</span>
            <button v-if="searchTerm" @click="searchTerm = ''" class="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-white transition-colors p-1 rounded-lg hover:bg-white/10">✕</button>
          </div>
          <div class="flex items-center gap-2 bg-white/10 rounded-lg p-1">
            <button @click="viewMode = 'grid'" :class="viewMode === 'grid' ? 'bg-purple-600 shadow-lg' : 'hover:bg-white/10'" class="p-2 rounded-lg text-white transition-all duration-300 transform hover:scale-110" title="Vista en cuadrícula">⊞</button>
            <button @click="viewMode = 'list'" :class="viewMode === 'list' ? 'bg-purple-600 shadow-lg' : 'hover:bg-white/10'" class="p-2 rounded-lg text-white transition-all duration-300 transform hover:scale-110" title="Vista en lista">☰</button>
          </div>
        </div>
      </div>

      <div v-if="error" class="mb-8">
        <div class="bg-yellow-900/30 border-l-4 border-yellow-500 text-yellow-300 p-4 rounded-xl">
          <p class="font-medium flex items-center gap-2">⚠️ {{ error }}</p>
        </div>
      </div>

      <div class="flex flex-col lg:flex-row gap-8">
        <aside class="w-full lg:w-64 flex-shrink-0">
          <ProductFilters
            :filters="filters"
            :filter-options="filterOptions"
            @update="handleFiltersChange"
            @clear="clearFilters"
          />
        </aside>

        <main class="w-full lg:flex-1 min-w-0">
          <div class="flex flex-col md:flex-row gap-4 justify-between items-center mb-6 flex-wrap">
            <div class="flex items-center gap-4 flex-1">
              <select
                v-model="sortBy"
                class="px-4 py-2 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all appearance-none pr-8"
                :style="sortSelectStyle"
              >
                <option value="name">📝 Nombre A-Z</option>
                <option value="price-low">💰 Precio: Menor a Mayor</option>
                <option value="price-high">💎 Precio: Mayor a Menor</option>
                <option value="rating">⭐ Mejor Calificados</option>
                <option value="newest">🆕 Más Nuevos</option>
              </select>

              <div v-if="getActiveFiltersCount > 0" class="flex items-center gap-2 flex-wrap">
                <span class="text-sm text-purple-300 bg-purple-900/30 px-3 py-1 rounded-full">
                  {{ getActiveFiltersCount }} filtro{{ getActiveFiltersCount !== 1 ? 's' : '' }} activo{{ getActiveFiltersCount !== 1 ? 's' : '' }}
                </span>
                <button @click="clearFilters" class="text-sm text-purple-400 hover:text-purple-300 font-medium">Limpiar</button>
              </div>
            </div>

            <div class="text-sm text-gray-400">
              {{ filteredProducts.length }} producto{{ filteredProducts.length !== 1 ? 's' : '' }} encontrado{{ filteredProducts.length !== 1 ? 's' : '' }}
            </div>
          </div>

          <div v-if="error" class="mb-6">
            <div class="bg-yellow-900/30 border-l-4 border-yellow-500 text-yellow-300 p-4 rounded-xl">
              <p class="font-medium flex items-center gap-2">⚠️ {{ error }}</p>
            </div>
          </div>

          <div v-if="loading" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            <div v-for="i in 8" :key="i" class="animate-pulse">
              <div class="bg-white/10 rounded-2xl overflow-hidden border border-white/20">
                <div class="aspect-square bg-white/5"></div>
                <div class="p-5 space-y-3">
                  <div class="h-4 bg-white/10 rounded w-3/4"></div>
                  <div class="h-3 bg-white/5 rounded w-full"></div>
                  <div class="h-6 bg-white/10 rounded w-1/3"></div>
                </div>
              </div>
            </div>
          </div>

          <div v-else-if="filteredProducts.length === 0" class="text-center py-16 animate-fade-in-up">
            <div class="bg-white/5 rounded-2xl p-12 border border-white/10">
              <div class="text-6xl mb-4">🔍</div>
              <h3 class="text-2xl font-bold text-white mb-2">No se encontraron productos</h3>
              <p class="text-gray-400 mb-6">Intenta cambiar los filtros o el término de búsqueda</p>
              <Button @click="clearFilters" icon="🔄" class="transform hover:scale-105">Limpiar Filtros</Button>
            </div>
          </div>

          <div v-else :class="viewMode === 'grid' ? 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6' : 'space-y-4'">
            <ProductCard
              v-for="(product, index) in filteredProducts"
              :key="product.id"
              :product="product"
              :view-mode="viewMode"
              :is-in-comparison="comparisonItems.some(item => item.id === product.id)"
              @add-to-cart="addToCart"
              @quick-view="openQuickView"
              @add-to-comparison="addToComparison"
              @navigate="navigateToProduct"
              :style="{ animationDelay: `${index * 50}ms` }"
            />
          </div>

          <div v-if="filteredProducts.length > 0" class="mt-8 flex justify-center gap-2 animate-fade-in-up">
            <Button variant="outline" @click="prevPage" :disabled="currentPage === 1">Anterior</Button>
            <span class="px-4 py-2 bg-white/10 text-white rounded-lg font-medium">
              Página {{ currentPage }}
            </span>
            <Button @click="nextPage">Siguiente</Button>
          </div>
        </main>
      </div>
    </div>

    <ProductQuickView
      :product="quickViewProduct"
      @close="closeQuickView"
      @add-to-cart="addToCart"
      @navigate="navigateToProduct"
    />

    <ProductComparison
      v-if="comparisonItems.length > 0"
      :items="comparisonItems"
      @remove="removeFromComparison"
      @navigate="navigateToProduct"
      @clear="clearComparison"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { productsAPI } from '../api'
import { useCartStore } from '../stores/cart'
import type { Product } from '../types'
import ProductCard from '../components/ProductCard.vue'
import ProductQuickView from '../components/ProductQuickView.vue'
import ProductFilters from '../components/ProductFilters.vue'
import ProductComparison from '../components/ProductComparison.vue'
import { getProductImage } from '../utils/productImages'
import Button from '../components/ui/Button.vue'

const router = useRouter()
const cartStore = useCartStore()

const products = ref<Product[]>([])
const loading = ref(true)
const error = ref('')
const searchTerm = ref('')
const viewMode = ref<'grid' | 'list'>('grid')
const quickViewProduct = ref<Product | null>(null)
const comparisonItems = ref<Product[]>([])
const currentPage = ref(1)

const filters = ref({
  category: '',
  priceRange: 1000,
  inStock: false
})

const filterOptions = computed(() => {
  const categories = Array.from(new Set(products.value.map(p => p.category).filter(Boolean)))
  const prices = products.value.map(p => p.price).filter(p => p > 0)
  const priceRange: [number, number] = prices.length > 0
    ? [Math.floor(Math.min(...prices)), Math.ceil(Math.max(...prices))]
    : [0, 1000]

  return {
    categories: categories.length > 0 ? categories : ['hombre', 'mujer', 'zapatos', 'accesorios'],
    priceRange
  }
})

const filteredProducts = computed(() => {
  let filtered = [...products.value]

  if (searchTerm.value) {
    filtered = filtered.filter(product =>
      product.name.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
      (product.description || '').toLowerCase().includes(searchTerm.value.toLowerCase()) ||
      (product.brand || '').toLowerCase().includes(searchTerm.value.toLowerCase())
    )
  }

  if (filters.value.category) {
    filtered = filtered.filter(p => p.category === filters.value.category)
  }

  if (filters.value.inStock) {
    filtered = filtered.filter(p => p.stock > 0)
  }

  filtered = filtered.filter(p => p.price >= filterOptions.value.priceRange[0] && p.price <= filters.value.priceRange)

  filtered.sort((a, b) => {
    switch (sortBy.value) {
      case 'price-low': return a.price - b.price
      case 'price-high': return b.price - a.price
      case 'rating': return ((b.averageRating || b.rating || 0) - (a.averageRating || a.rating || 0))
      case 'newest': return new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime()
      default: return a.name.localeCompare(b.name)
    }
  })

  return filtered
})

const sortBy = ref('name')

const getActiveFiltersCount = computed(() => {
  let count = 0
  if (filters.value.category) count++
  if (filters.value.inStock) count++
  if (filters.value.priceRange !== filterOptions.value.priceRange[1]) count++
  return count
})

const sortSelectStyle = computed(() => ({
  backgroundImage: 'url(\'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="%23a855f7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>\')',
  backgroundPosition: 'right 0.75rem center',
  backgroundSize: '1.25rem',
  backgroundRepeat: 'no-repeat',
  webkitAppearance: 'none',
  mozAppearance: 'none',
  paddingRight: '2.5rem'
}))

const handleFiltersChange = (newFilters: any) => {
  filters.value = newFilters
  currentPage.value = 1
}

const clearFilters = () => {
  filters.value = {
    category: '',
    priceRange: filterOptions.value.priceRange[1],
    inStock: false
  }
  searchTerm.value = ''
  currentPage.value = 1
}

const addToCart = (product: Product) => {
  cartStore.addItem(product, 1)
}

const openQuickView = (product: Product) => {
  quickViewProduct.value = product
}

const closeQuickView = () => {
  quickViewProduct.value = null
}

const addToComparison = (product: Product) => {
  if (comparisonItems.value.length < 3 && !comparisonItems.value.find(item => item.id === product.id)) {
    comparisonItems.value.push(product)
  }
}

const removeFromComparison = (productId: number) => {
  comparisonItems.value = comparisonItems.value.filter(item => item.id !== productId)
}

const clearComparison = () => {
  comparisonItems.value = []
}

const navigateToProduct = (id: number) => {
  router.push(`/product/${id}`)
}

const prevPage = () => {
  if (currentPage.value > 1) currentPage.value--
}

const nextPage = () => {
  // pagination logic here
}

const fetchProducts = async () => {
  loading.value = true
  error.value = ''
  try {
    const response = await productsAPI.getAll()
    const backendProducts = response.data || []
    products.value = backendProducts.map(product => ({
      ...product,
      price: typeof product.price === 'string' ? parseFloat(product.price) : (product.price || 0),
      stock: typeof product.stock === 'string' ? parseInt(product.stock) : (product.stock || 0),
      imageUrl: getProductImage(product.name, product.category, product.imageUrl || product.image),
      brand: product.brand || 'Sin marca',
      colors: product.colors || [],
      sizes: product.sizes || [],
      isNew: product.isNew || false,
      isFeatured: product.isFeatured || false,
      isOnSale: product.isOnSale || false,
      isBestseller: product.isBestseller || false,
      rating: product.rating || 0,
      averageRating: product.averageRating || 0,
      reviewCount: product.reviewCount || 0
    }))
  } catch (err) {
    error.value = 'Conectando con el backend. Esto puede tardar unos segundos.'
    console.error(err)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchProducts()
})

watch(() => filterOptions.value.priceRange, (newRange) => {
  if (filters.value.priceRange === filterOptions.value.priceRange[1] || filters.value.priceRange > newRange[1]) {
    filters.value.priceRange = newRange[1]
  }
}, { immediate: true })
</script>

<style scoped>
.animate-fade-in-up {
  animation: fadeInUp 0.6s ease-out forwards;
  opacity: 0;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
