// tienda-frontend/src/pages/ReturnRequest.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 py-12 px-4 relative overflow-hidden">
    <div class="fixed inset-0 overflow-hidden pointer-events-none">
      <div class="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-red-500/20 to-orange-500/20 rounded-full blur-3xl animate-pulse"></div>
      <div class="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
    </div>

    <div class="max-w-4xl mx-auto relative z-10">
      <div class="mb-8">
        <h1 class="text-4xl font-bold text-white flex items-center gap-3">
          🔄 Solicitar Devolución
        </h1>
        <p v-if="order" class="text-gray-300 text-lg mt-2">Pedido #{{ order.orderNumber }}</p>
      </div>

      <div v-if="loading" class="animate-pulse space-y-6">
        <div class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
          <div class="space-y-4">
            <div v-for="i in 3" :key="i" class="flex items-center justify-between p-4 bg-white/5 rounded-xl">
              <div class="flex items-center gap-4">
                <div class="w-5 h-5 bg-white/10 rounded"></div>
                <div class="w-12 h-12 bg-white/5 rounded"></div>
                <div class="space-y-2">
                  <div class="h-4 bg-white/5 rounded w-32"></div>
                  <div class="h-3 bg-white/5 rounded w-24"></div>
                </div>
              </div>
              <div class="h-4 bg-white/5 rounded w-16"></div>
            </div>
          </div>
        </div>
      </div>

      <div v-else-if="error && !order" class="bg-red-500/20 border border-red-500/50 rounded-2xl p-8 text-center">
        <div class="text-6xl mb-4">❌</div>
        <p class="text-red-300 text-lg">{{ error }}</p>
        <button @click="router.push('/orders')" class="mt-6 px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700">
          Volver a Mis Pedidos
        </button>
      </div>

      <form v-else-if="order" @submit.prevent="handleSubmit" class="space-y-6">
        <div v-if="submitError" class="bg-red-500/20 border border-red-500/50 rounded-xl p-4 text-red-300">
          {{ submitError }}
        </div>

        <div class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
          <h3 class="text-xl font-semibold text-white mb-4">Selecciona los productos a devolver</h3>
          
          <div class="space-y-3">
            <div 
              v-for="item in order.items" 
              :key="item.id"
              class="flex items-center justify-between p-4 bg-white/5 rounded-xl"
            >
              <div class="flex items-center gap-4">
                <input 
                  type="checkbox" 
                  :id="`item-${item.id}`"
                  :checked="selectedItems.has(item.id)"
                  @change="toggleItem(item, ($event.target as HTMLInputElement).checked)"
                  class="w-5 h-5 rounded text-purple-500"
                />
                <div class="text-4xl">{{ getProductEmoji(item.product?.category) }}</div>
                <div>
                  <p class="text-white font-medium">{{ item.product?.name || 'Producto' }}</p>
                  <p class="text-gray-400 text-sm">Cantidad: {{ item.quantity }} - S/ {{ Number(item.price).toFixed(2) }}</p>
                </div>
              </div>
              <p class="text-purple-400 font-bold">S/ {{ (item.price * item.quantity).toFixed(2) }}</p>
            </div>
          </div>
        </div>

        <div v-if="selectedItems.size > 0" class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
          <h3 class="text-xl font-semibold text-white mb-4">Detalles de la devolución</h3>
          
          <div class="space-y-4">
            <div>
              <label class="text-gray-300 text-sm mb-2 block">Motivo de la devolución *</label>
              <select v-model="returnReason" required class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white">
                <option value="" class="text-gray-900">Selecciona un motivo</option>
                <option value="defectuoso" class="text-gray-900">Producto defectuoso</option>
                <option value="talla" class="text-gray-900">Talla incorrecta</option>
                <option value="color" class="text-gray-900">Color diferente al mostrado</option>
                <option value="dañado" class="text-gray-900">Llegó dañado</option>
                <option value="no_necesito" class="text-gray-900">Ya no lo necesito</option>
                <option value="otro" class="text-gray-900">Otro motivo</option>
              </select>
            </div>

            <div>
              <label class="text-gray-300 text-sm mb-2 block">Descripción detallada *</label>
              <textarea 
                v-model="description" 
                required
                rows="4"
                class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white placeholder-gray-400"
                placeholder="Describe el problema con el producto..."
              ></textarea>
            </div>

            <div class="flex items-center justify-between p-4 bg-purple-500/20 rounded-xl border border-purple-500/30">
              <span class="text-white font-semibold">Monto a reembolsar:</span>
              <span class="text-2xl font-bold text-purple-400">S/ {{ calculateRefund().toFixed(2) }}</span>
            </div>
          </div>
        </div>

        <div class="flex gap-4">
          <button 
            type="button" 
            @click="router.push('/orders')"
            class="flex-1 px-6 py-3 border border-white/30 text-white rounded-xl hover:bg-white/10"
          >
            Cancelar
          </button>
          <button 
            type="submit" 
            :disabled="submitting || selectedItems.size === 0"
            class="flex-1 px-6 py-3 bg-gradient-to-r from-red-500 to-orange-500 text-white rounded-xl hover:from-red-600 hover:to-orange-600 disabled:opacity-50"
          >
            {{ submitting ? 'Enviando...' : 'Enviar Solicitud' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ordersAPI } from '../api'

const route = useRoute()
const router = useRouter()

interface OrderItem {
  id: number
  quantity: number
  price: number
  product: {
    id: number
    name: string
    category?: string
    imageUrl?: string
  }
}

interface Order {
  id: number
  orderNumber: string
  status: string
  total: number
  items: OrderItem[]
  canBeReturned: boolean
}

interface SelectedItem {
  orderItemId: number
  quantity: number
  condition?: string
  notes?: string
}

const order = ref<Order | null>(null)
const loading = ref(true)
const submitting = ref(false)
const submitError = ref('')
const returnReason = ref('')
const description = ref('')
const selectedItems = ref<Map<number, SelectedItem>>(new Map())

const getProductEmoji = (category?: string): string => {
  if (!category) return String.fromCodePoint(0x1F455)
  const cat = category.toLowerCase()
  if (cat.includes('hombre') || cat.includes('men')) return String.fromCodePoint(0x1F455)
  if (cat.includes('mujer') || cat.includes('women')) return String.fromCodePoint(0x1F457)
  if (cat.includes('shoes') || cat.includes('zapato')) return String.fromCodePoint(0x1F45F)
  if (cat.includes('accessories') || cat.includes('accesorio')) return String.fromCodePoint(0x1F6C1)
  return String.fromCodePoint(0x1F455)
}

const toggleItem = (item: OrderItem, selected: boolean) => {
  if (selected) {
    selectedItems.value.set(item.id, {
      orderItemId: item.id,
      quantity: item.quantity,
      condition: '',
      notes: ''
    })
  } else {
    selectedItems.value.delete(item.id)
  }
}

const calculateRefund = (): number => {
  let total = 0
  selectedItems.value.forEach((returnItem, orderItemId) => {
    const orderItem = order.value?.items.find(i => i.id === orderItemId)
    if (orderItem) {
      total += orderItem.price * returnItem.quantity
    }
  })
  return total
}

const fetchOrder = async () => {
  try {
    const orderId = route.params.orderId
    const response = await ordersAPI.getById(Number(orderId))
    order.value = response.data
    
    if (!response.data.canBeReturned) {
      submitError.value = 'Este pedido no puede ser devuelto'
    }
  } catch (err: any) {
    submitError.value = err.response?.data?.message || 'Error al cargar el pedido'
  } finally {
    loading.value = false
  }
}

const handleSubmit = async () => {
  if (selectedItems.value.size === 0) {
    submitError.value = 'Debes seleccionar al menos un producto para devolver'
    return
  }
  
  if (!returnReason.value || !description.value.trim()) {
    submitError.value = 'Debes completar todos los campos obligatorios'
    return
  }

  submitting.value = true
  submitError.value = ''

  try {
    const orderId = route.params.orderId as string
    await ordersAPI.createReturn(Number(orderId), {
      reason: returnReason.value,
      description: description.value.trim(),
      items: Array.from(selectedItems.value.values())
    })

    router.push('/orders')
  } catch (err: any) {
    submitError.value = err.response?.data?.message || 'Error al crear la solicitud de devolución'
  } finally {
    submitting.value = false
  }
}

onMounted(() => {
  fetchOrder()
})
</script>

// tienda-frontend/src/pages/ReturnRequest.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { API_BASE_URL } from '../services/api';

interface OrderItem {
  id: number;
  quantity: number;
  price: number;
  product: {
    id: number;
    name: string;
    imageUrl?: string;
  };
}

interface Order {
  id: number;
  orderNumber: string;
  status: string;
  total: number;
  items: OrderItem[];
  canBeReturned: boolean;
}

interface ReturnItem {
  orderItemId: number;
  quantity: number;
  condition?: string;
  notes?: string;
}

const ReturnRequest: React.FC = () => {
  const { orderId } = useParams<{ orderId: string }>();
  const navigate = useNavigate();
  const [order, setOrder] = useState<Order | null>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [returnReason, setReturnReason] = useState('');
  const [description, setDescription] = useState('');
  const [selectedItems, setSelectedItems] = useState<Map<number, ReturnItem>>(new Map());

  useEffect(() => {
    fetchOrder();
  }, [orderId]);

  const fetchOrder = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`${API_BASE_URL}/orders/${orderId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setOrder(response.data);
      
      if (!response.data.canBeReturned) {
        setError('Este pedido no puede ser devuelto');
      }
    } catch (err: any) {
      setError(err.response?.data?.message || 'Error fetching order');
    } finally {
      setLoading(false);
    }
  };

  const handleItemSelection = (orderItem: OrderItem, selected: boolean) => {
    const newSelectedItems = new Map(selectedItems);
    
    if (selected) {
      newSelectedItems.set(orderItem.id, {
        orderItemId: orderItem.id,
        quantity: orderItem.quantity,
        condition: '',
        notes: ''
      });
    } else {
      newSelectedItems.delete(orderItem.id);
    }
    
    setSelectedItems(newSelectedItems);
  };

  const updateReturnItem = (orderItemId: number, field: keyof ReturnItem, value: string | number) => {
    const newSelectedItems = new Map(selectedItems);
    const item = newSelectedItems.get(orderItemId);
    
    if (item) {
      newSelectedItems.set(orderItemId, {
        ...item,
        [field]: value
      });
      setSelectedItems(newSelectedItems);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (selectedItems.size === 0) {
      setError('Debes seleccionar al menos un producto para devolver');
      return;
    }
    
    if (!returnReason || !description.trim()) {
      setError('Debes completar todos los campos obligatorios');
      return;
    }

    setSubmitting(true);
    setError(null);

    try {
      const token = localStorage.getItem('token');
      const returnData = {
        orderId: parseInt(orderId!),
        reason: returnReason,
        description: description.trim(),
        items: Array.from(selectedItems.values())
      };

      await axios.post(`${API_BASE_URL}/orders/${orderId}/returns`, returnData, {
        headers: { Authorization: `Bearer ${token}` }
      });

      // Redirect to orders page with success message
      navigate('/orders', { 
        state: { 
          message: 'Solicitud de devolución enviada exitosamente. Te contactaremos pronto.' 
        }
      });
    } catch (err: any) {
      setError(err.response?.data?.message || 'Error creating return request');
    } finally {
      setSubmitting(false);
    }
  };

  const calculateRefundAmount = () => {
    let total = 0;
    selectedItems.forEach((returnItem, orderItemId) => {
      const orderItem = order?.items.find(item => item.id === orderItemId);
      if (orderItem) {
        total += orderItem.price * returnItem.quantity;
      }
    });
    return total;
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Cargando información del pedido...</p>
        </div>
      </div>
    );
  }

  if (error && !order) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="text-red-600 text-xl mb-4">❌</div>
          <p className="text-red-600">{error}</p>
          <button
            onClick={() => navigate('/orders')}
            className="mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700"
          >
            Volver a Mis Pedidos
          </button>
        </div>
      </div>
    );
  }

  if (!order) return null;

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Solicitar Devolución</h1>
          <p className="mt-2 text-gray-600">Pedido #{order.orderNumber}</p>
        </div>

        {error && (
          <div className="mb-6 bg-red-50 border border-red-200 rounded-md p-4">
            <div className="flex">
              <div className="ml-3">
                <h3 className="text-sm font-medium text-red-800">Error</h3>
                <div className="mt-2 text-sm text-red-700">{error}</div>
              </div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Return Reason */}
          <div className="bg-white shadow rounded-lg p-6">
            <h2 className="text-lg font-medium text-gray-900 mb-4">Motivo de la Devolución</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  ¿Por qué quieres devolver este pedido? *
                </label>
                <select
                  value={returnReason}
                  onChange={(e) => setReturnReason(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                >
                  <option value="">Selecciona un motivo</option>
                  <option value="defective">Producto defectuoso</option>
                  <option value="wrong_size">Talla incorrecta</option>
                  <option value="not_as_described">No es como se describe</option>
                  <option value="changed_mind">Cambié de opinión</option>
                  <option value="damaged_in_shipping">Dañado en el envío</option>
                  <option value="other">Otro motivo</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Descripción detallada *
                </label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={4}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Explica en detalle el motivo de la devolución..."
                  required
                />
              </div>
            </div>
          </div>

          {/* Items Selection */}
          <div className="bg-white shadow rounded-lg p-6">
            <h2 className="text-lg font-medium text-gray-900 mb-4">Productos a Devolver</h2>
            <div className="space-y-4">
              {order.items.map((item) => (
                <div key={item.id} className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-start space-x-4">
                    <input
                      type="checkbox"
                      checked={selectedItems.has(item.id)}
                      onChange={(e) => handleItemSelection(item, e.target.checked)}
                      className="mt-1 h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                    />
                    <div className="flex-shrink-0 w-16 h-16 bg-gray-200 rounded-md flex items-center justify-center">
                      {item.product.imageUrl ? (
                        <img
                          src={item.product.imageUrl}
                          alt={item.product.name}
                          className="w-full h-full object-cover rounded-md"
                        />
                      ) : (
                        <span className="text-gray-400 text-xs">Sin imagen</span>
                      )}
                    </div>
                    <div className="flex-1">
                      <h3 className="text-sm font-medium text-gray-900">{item.product.name}</h3>
                      <p className="text-sm text-gray-600">
                        Precio: ${item.price.toFixed(2)} × {item.quantity}
                      </p>
                      <p className="text-sm font-medium text-gray-900">
                        Total: ${(item.price * item.quantity).toFixed(2)}
                      </p>
                      
                      {selectedItems.has(item.id) && (
                        <div className="mt-3 space-y-3">
                          <div>
                            <label className="block text-xs font-medium text-gray-700 mb-1">
                              Cantidad a devolver
                            </label>
                            <input
                              type="number"
                              min="1"
                              max={item.quantity}
                              value={selectedItems.get(item.id)?.quantity || item.quantity}
                              onChange={(e) => updateReturnItem(item.id, 'quantity', parseInt(e.target.value))}
                              className="w-20 px-2 py-1 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </div>
                          <div>
                            <label className="block text-xs font-medium text-gray-700 mb-1">
                              Condición del producto
                            </label>
                            <select
                              value={selectedItems.get(item.id)?.condition || ''}
                              onChange={(e) => updateReturnItem(item.id, 'condition', e.target.value)}
                              className="w-full px-2 py-1 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                            >
                              <option value="">Seleccionar condición</option>
                              <option value="new">Nuevo/Sin usar</option>
                              <option value="used">Usado</option>
                              <option value="damaged">Dañado</option>
                              <option value="defective">Defectuoso</option>
                            </select>
                          </div>
                          <div>
                            <label className="block text-xs font-medium text-gray-700 mb-1">
                              Notas adicionales
                            </label>
                            <textarea
                              value={selectedItems.get(item.id)?.notes || ''}
                              onChange={(e) => updateReturnItem(item.id, 'notes', e.target.value)}
                              rows={2}
                              className="w-full px-2 py-1 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                              placeholder="Información adicional sobre este producto..."
                            />
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Summary */}
          {selectedItems.size > 0 && (
            <div className="bg-white shadow rounded-lg p-6">
              <h2 className="text-lg font-medium text-gray-900 mb-4">Resumen de Devolución</h2>
              <div className="space-y-2">
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Productos seleccionados:</span>
                  <span className="text-sm font-medium">{selectedItems.size}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Monto estimado de reembolso:</span>
                  <span className="text-lg font-bold text-green-600">
                    ${calculateRefundAmount().toFixed(2)}
                  </span>
                </div>
              </div>
              <p className="mt-4 text-xs text-gray-500">
                * El monto final del reembolso puede variar según la condición de los productos recibidos.
              </p>
            </div>
          )}

          {/* Submit Button */}
          <div className="flex justify-end space-x-4">
            <button
              type="button"
              onClick={() => navigate('/orders')}
              className="px-6 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50"
            >
              Cancelar
            </button>
            <button
              type="submit"
              disabled={submitting || selectedItems.size === 0}
              className="px-6 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {submitting ? 'Enviando...' : 'Solicitar Devolución'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ReturnRequest;
