// tienda-frontend/tienda-vue/src/pages/SupplierManagement.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 py-12 px-4 relative overflow-hidden">
    <div class="fixed inset-0 overflow-hidden pointer-events-none">
      <div class="absolute -top-40 -right-40 w-96 h-96 bg-gradient-to-br from-yellow-500/20 to-orange-500/20 rounded-full blur-3xl animate-pulse"></div>
      <div class="absolute -bottom-40 -left-40 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
    </div>

    <div class="max-w-7xl mx-auto relative z-10">
      <div class="bg-gradient-to-r from-yellow-600 via-orange-600 to-red-600 rounded-2xl p-8 text-white shadow-2xl mb-8">
        <div class="flex justify-between items-center">
          <div>
            <h1 class="text-4xl font-extrabold flex items-center gap-3">
              🚚 Gestión de Proveedores
            </h1>
            <p class="text-yellow-100 text-lg mt-2">Administra tus proveedores y relaciones comerciales</p>
          </div>
          <button 
            @click="showAddModal = true"
            class="px-6 py-3 bg-white/20 text-white rounded-xl font-semibold hover:bg-white/30"
          >
            + Nuevo Proveedor
          </button>
        </div>
      </div>

      <div class="flex gap-4 mb-6">
        <button 
          @click="activeTab = 'list'"
          :class="activeTab === 'list' ? 'bg-purple-600 text-white' : 'bg-white/10 text-gray-300'"
          class="px-6 py-2 rounded-xl font-semibold transition-all"
        >
          📋 Lista de Proveedores
        </button>
        <button 
          @click="activeTab = 'stats'"
          :class="activeTab === 'stats' ? 'bg-purple-600 text-white' : 'bg-white/10 text-gray-300'"
          class="px-6 py-2 rounded-xl font-semibold transition-all"
        >
          📊 Estadísticas
        </button>
      </div>

      <div v-if="loading" class="flex items-center justify-center py-20">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500"></div>
      </div>

      <div v-else-if="activeTab === 'list'" class="space-y-4">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div 
            v-for="supplier in suppliers" 
            :key="supplier.id"
            class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6 hover:border-purple-500/50 transition-all cursor-pointer"
            @click="selectSupplier(supplier)"
          >
            <div class="flex items-start justify-between mb-4">
              <div>
                <h3 class="text-white font-bold text-xl">{{ supplier.name }}</h3>
                <p class="text-gray-400 text-sm">Código: {{ supplier.code }}</p>
              </div>
              <span 
                :class="supplier.isActive ? 'bg-green-500/30 text-green-300' : 'bg-red-500/30 text-red-300'"
                class="px-3 py-1 rounded-full text-xs"
              >
                {{ supplier.isActive ? 'Activo' : 'Inactivo' }}
              </span>
            </div>

            <div class="space-y-2 text-sm">
              <p class="text-gray-300">📧 {{ supplier.email || 'Sin email' }}</p>
              <p class="text-gray-300">📞 {{ supplier.phone || 'Sin teléfono' }}</p>
              <p class="text-gray-300">🏙️ {{ supplier.city || 'Sin ciudad' }}, {{ supplier.country || 'Sin país' }}</p>
            </div>

            <div class="flex items-center justify-between mt-4 pt-4 border-t border-white/10">
              <div class="flex items-center gap-1">
                <span class="text-yellow-400">★</span>
                <span class="text-white font-semibold">{{ supplier.rating }}</span>
              </div>
              <span class="text-gray-400 text-sm">{{ supplier.totalOrders }} pedidos</span>
            </div>
          </div>
        </div>

        <div v-if="suppliers.length === 0" class="text-center py-12">
          <div class="text-6xl mb-4">📦</div>
          <p class="text-gray-400 text-lg">No hay proveedores registrados</p>
          <button 
            @click="showAddModal = true"
            class="mt-4 px-6 py-3 bg-purple-600 text-white rounded-xl hover:bg-purple-700"
          >
            Agregar Primer Proveedor
          </button>
        </div>
      </div>

      <div v-else-if="activeTab === 'stats'" class="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
          <div class="text-4xl mb-2">🏢</div>
          <p class="text-gray-400 text-sm">Total Proveedores</p>
          <p class="text-3xl font-bold text-white">{{ suppliers.length }}</p>
        </div>
        <div class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
          <div class="text-4xl mb-2">✅</div>
          <p class="text-gray-400 text-sm">Activos</p>
          <p class="text-3xl font-bold text-green-400">{{ activeSuppliers }}</p>
        </div>
        <div class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
          <div class="text-4xl mb-2">📦</div>
          <p class="text-gray-400 text-sm">Total Pedidos</p>
          <p class="text-3xl font-bold text-blue-400">{{ totalOrders }}</p>
        </div>
        <div class="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6">
          <div class="text-4xl mb-2">💰</div>
          <p class="text-gray-400 text-sm">Total Gastado</p>
          <p class="text-3xl font-bold text-yellow-400">S/ {{ totalSpent.toFixed(2) }}</p>
        </div>
      </div>

      <div v-if="selectedSupplier" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div class="bg-gray-900 border border-white/20 rounded-2xl p-6 max-w-2xl w-full max-h-[90vh] overflow-y-auto">
          <div class="flex justify-between items-start mb-6">
            <h2 class="text-2xl font-bold text-white">{{ selectedSupplier.name }}</h2>
            <button @click="selectedSupplier = null" class="text-gray-400 hover:text-white text-2xl">✕</button>
          </div>

          <div class="space-y-4">
            <div class="grid grid-cols-2 gap-4">
              <div class="bg-white/5 rounded-xl p-4">
                <p class="text-gray-400 text-sm">Código</p>
                <p class="text-white font-semibold">{{ selectedSupplier.code }}</p>
              </div>
              <div class="bg-white/5 rounded-xl p-4">
                <p class="text-gray-400 text-sm">Estado</p>
                <span :class="selectedSupplier.isActive ? 'text-green-400' : 'text-red-400'" class="font-semibold">
                  {{ selectedSupplier.isActive ? 'Activo' : 'Inactivo' }}
                </span>
              </div>
              <div class="bg-white/5 rounded-xl p-4">
                <p class="text-gray-400 text-sm">Persona de Contacto</p>
                <p class="text-white">{{ selectedSupplier.contactPerson || 'No definido' }}</p>
              </div>
              <div class="bg-white/5 rounded-xl p-4">
                <p class="text-gray-400 text-sm">Teléfono</p>
                <p class="text-white">{{ selectedSupplier.phone || 'No definido' }}</p>
              </div>
            </div>

            <div class="bg-white/5 rounded-xl p-4">
              <p class="text-gray-400 text-sm mb-2">Dirección</p>
              <p class="text-white">{{ selectedSupplier.address || 'No definida' }}, {{ selectedSupplier.city }}, {{ selectedSupplier.country }}</p>
            </div>

            <div class="bg-white/5 rounded-xl p-4">
              <p class="text-gray-400 text-sm mb-2">Términos de Pago</p>
              <p class="text-white">{{ selectedSupplier.paymentTerms }}</p>
            </div>

            <div class="flex gap-4">
              <button 
                @click="editSupplier(selectedSupplier)"
                class="flex-1 px-4 py-2 bg-yellow-600 text-white rounded-xl hover:bg-yellow-700"
              >
                ✏️ Editar
              </button>
              <button 
                @click="toggleSupplierStatus(selectedSupplier)"
                class="flex-1 px-4 py-2 bg-red-600 text-white rounded-xl hover:bg-red-700"
              >
                {{ selectedSupplier.isActive ? '❌ Desactivar' : '✅ Activar' }}
              </button>
            </div>
          </div>
        </div>
      </div>

      <div v-if="showAddModal" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div class="bg-gray-900 border border-white/20 rounded-2xl p-6 max-w-xl w-full">
          <h2 class="text-2xl font-bold text-white mb-6">Agregar Nuevo Proveedor</h2>
          
          <form @submit.prevent="addSupplier" class="space-y-4">
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="text-gray-400 text-sm mb-1 block">Nombre *</label>
                <input v-model="newSupplier.name" required class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div>
                <label class="text-gray-400 text-sm mb-1 block">Código *</label>
                <input v-model="newSupplier.code" required class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div>
                <label class="text-gray-400 text-sm mb-1 block">Persona de Contacto</label>
                <input v-model="newSupplier.contactPerson" class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div>
                <label class="text-gray-400 text-sm mb-1 block">Teléfono</label>
                <input v-model="newSupplier.phone" class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div class="col-span-2">
                <label class="text-gray-400 text-sm mb-1 block">Email</label>
                <input v-model="newSupplier.email" type="email" class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div class="col-span-2">
                <label class="text-gray-400 text-sm mb-1 block">Dirección</label>
                <input v-model="newSupplier.address" class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div>
                <label class="text-gray-400 text-sm mb-1 block">Ciudad</label>
                <input v-model="newSupplier.city" class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div>
                <label class="text-gray-400 text-sm mb-1 block">País</label>
                <input v-model="newSupplier.country" class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white" />
              </div>
              <div class="col-span-2">
                <label class="text-gray-400 text-sm mb-1 block">Términos de Pago</label>
                <select v-model="newSupplier.paymentTerms" class="w-full bg-white/10 border border-white/20 rounded-xl p-3 text-white">
                  <option value="contado" class="text-gray-900">Contado</option>
                  <option value="net15" class="text-gray-900">Net 15 días</option>
                  <option value="net30" class="text-gray-900">Net 30 días</option>
                  <option value="net45" class="text-gray-900">Net 45 días</option>
                  <option value="net60" class="text-gray-900">Net 60 días</option>
                </select>
              </div>
            </div>

            <div class="flex gap-4 pt-4">
              <button type="button" @click="showAddModal = false" class="flex-1 px-4 py-2 border border-white/30 text-white rounded-xl hover:bg-white/10">
                Cancelar
              </button>
              <button type="submit" class="flex-1 px-4 py-2 bg-green-600 text-white rounded-xl hover:bg-green-700">
                Guardar
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import api from '../api'

interface Supplier {
  id: number
  name: string
  code: string
  contactPerson?: string
  email?: string
  phone?: string
  address?: string
  city?: string
  country?: string
  paymentTerms: string
  rating: number
  isActive: boolean
  totalOrders: number
  totalSpent: number
  lastOrderDate?: string
}

const suppliers = ref<Supplier[]>([])
const selectedSupplier = ref<Supplier | null>(null)
const loading = ref(true)
const activeTab = ref('list')
const showAddModal = ref(false)

const newSupplier = ref({
  name: '',
  code: '',
  contactPerson: '',
  email: '',
  phone: '',
  address: '',
  city: '',
  country: '',
  paymentTerms: 'net30',
  rating: 5
})

const activeSuppliers = computed(() => suppliers.value.filter(s => s.isActive).length)
const totalOrders = computed(() => suppliers.value.reduce((sum, s) => sum + s.totalOrders, 0))
const totalSpent = computed(() => suppliers.value.reduce((sum, s) => sum + s.totalSpent, 0))

const fetchSuppliers = async () => {
  try {
    const response = await api.get('/suppliers')
    suppliers.value = response.data?.data || response.data || []
  } catch (error) {
    console.error('Error fetching suppliers:', error)
  } finally {
    loading.value = false
  }
}

const selectSupplier = (supplier: Supplier) => {
  selectedSupplier.value = supplier
}

const addSupplier = async () => {
  try {
    await api.post('/suppliers', newSupplier.value)
    showAddModal.value = false
    newSupplier.value = {
      name: '',
      code: '',
      contactPerson: '',
      email: '',
      phone: '',
      address: '',
      city: '',
      country: '',
      paymentTerms: 'net30',
      rating: 5
    }
    fetchSuppliers()
  } catch (error) {
    console.error('Error adding supplier:', error)
  }
}

const editSupplier = (supplier: Supplier) => {
  console.log('Edit supplier:', supplier.id)
}

const toggleSupplierStatus = async (supplier: Supplier) => {
  try {
    await api.patch(`/suppliers/${supplier.id}`, { isActive: !supplier.isActive })
    fetchSuppliers()
    selectedSupplier.value = null
  } catch (error) {
    console.error('Error updating supplier:', error)
  }
}

onMounted(() => {
  fetchSuppliers()
})
</script>

// tienda-frontend/src/pages/SupplierManagement.tsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';

interface Supplier {
  id: number;
  name: string;
  code: string;
  contactPerson?: string;
  email?: string;
  phone?: string;
  address?: string;
  city?: string;
  country?: string;
  paymentTerms: string;
  rating: number;
  isActive: boolean;
  totalOrders: number;
  totalSpent: number;
  lastOrderDate?: string;
}

interface SupplierProduct {
  id: number;
  product: {
    id: number;
    name: string;
    sku: string;
  };
  supplierSku?: string;
  supplierPrice: number;
  minimumOrderQuantity: number;
  leadTimeDays: number;
  isPreferred: boolean;
  isActive: boolean;
}

const SupplierManagement: React.FC = () => {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [selectedSupplier, setSelectedSupplier] = useState<Supplier | null>(null);
  const [supplierProducts, setSupplierProducts] = useState<SupplierProduct[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [activeTab, setActiveTab] = useState('list');

  const [newSupplier, setNewSupplier] = useState({
    name: '',
    code: '',
    contactPerson: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    country: '',
    paymentTerms: 'net30',
    rating: 5,
    notes: ''
  });

  useEffect(() => {
    fetchSuppliers();
  }, []);

  const fetchSuppliers = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get('/api/suppliers', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setSuppliers(response.data);
    } catch (error) {
      console.error('Error fetching suppliers:', error);
    } finally {
      setLoading(false);
    }
  };

  const fetchSupplierProducts = async (supplierId: number) => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`/api/suppliers/${supplierId}/products`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setSupplierProducts(response.data);
    } catch (error) {
      console.error('Error fetching supplier products:', error);
    }
  };

  const handleAddSupplier = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const token = localStorage.getItem('token');
      await axios.post('/api/suppliers', newSupplier, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setShowAddModal(false);
      setNewSupplier({
        name: '',
        code: '',
        contactPerson: '',
        email: '',
        phone: '',
        address: '',
        city: '',
        country: '',
        paymentTerms: 'net30',
        rating: 5,
        notes: ''
      });
      fetchSuppliers();
    } catch (error) {
      console.error('Error adding supplier:', error);
    }
  };

  const handleUpdateSupplier = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedSupplier) return;

    try {
      const token = localStorage.getItem('token');
      await axios.put(`/api/suppliers/${selectedSupplier.id}`, selectedSupplier, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setShowEditModal(false);
      setSelectedSupplier(null);
      fetchSuppliers();
    } catch (error) {
      console.error('Error updating supplier:', error);
    }
  };

  const handleDeleteSupplier = async (supplierId: number) => {
    if (!confirm('¿Estás seguro de que quieres eliminar este proveedor?')) return;

    try {
      const token = localStorage.getItem('token');
      await axios.delete(`/api/suppliers/${supplierId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      fetchSuppliers();
    } catch (error) {
      console.error('Error deleting supplier:', error);
    }
  };

  const getRatingStars = (rating: number) => {
    return '⭐'.repeat(Math.floor(rating)) + '☆'.repeat(5 - Math.floor(rating));
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">🏭 Gestión de Proveedores</h1>
        <p className="text-gray-600 mt-2">Administra proveedores y sus productos</p>
      </div>

      {/* Navigation Tabs */}
      <div className="border-b border-gray-200 mb-6">
        <nav className="-mb-px flex space-x-8">
          {[
            { id: 'list', name: 'Lista de Proveedores', icon: '📋' },
            { id: 'performance', name: 'Rendimiento', icon: '📊' }
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`py-2 px-1 border-b-2 font-medium text-sm ${
                activeTab === tab.id
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              {tab.icon} {tab.name}
            </button>
          ))}
        </nav>
      </div>

      {/* Suppliers List Tab */}
      {activeTab === 'list' && (
        <div className="space-y-6">
          {/* Header with Add Button */}
          <div className="flex justify-between items-center">
            <h2 className="text-xl font-semibold text-gray-900">Proveedores</h2>
            <button
              onClick={() => setShowAddModal(true)}
              className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 flex items-center space-x-2"
            >
              <span>➕</span>
              <span>Agregar Proveedor</span>
            </button>
          </div>

          {/* Suppliers Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {suppliers.map((supplier) => (
              <div key={supplier.id} className="bg-white rounded-lg shadow-md p-6">
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900">{supplier.name}</h3>
                    <p className="text-sm text-gray-500">Código: {supplier.code}</p>
                  </div>
                  <div className="flex space-x-2">
                    <button
                      onClick={() => {
                        setSelectedSupplier(supplier);
                        setShowEditModal(true);
                      }}
                      className="text-blue-600 hover:text-blue-800"
                    >
                      ✏️
                    </button>
                    <button
                      onClick={() => handleDeleteSupplier(supplier.id)}
                      className="text-red-600 hover:text-red-800"
                    >
                      🗑️
                    </button>
                  </div>
                </div>

                <div className="space-y-2 text-sm">
                  {supplier.contactPerson && (
                    <p><span className="font-medium">Contacto:</span> {supplier.contactPerson}</p>
                  )}
                  {supplier.email && (
                    <p><span className="font-medium">Email:</span> {supplier.email}</p>
                  )}
                  {supplier.phone && (
                    <p><span className="font-medium">Teléfono:</span> {supplier.phone}</p>
                  )}
                  <p><span className="font-medium">Términos:</span> {supplier.paymentTerms}</p>
                  <p><span className="font-medium">Rating:</span> {getRatingStars(supplier.rating)}</p>
                </div>

                <div className="mt-4 pt-4 border-t border-gray-200">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-500">Órdenes:</span>
                    <span className="font-medium">{supplier.totalOrders}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-500">Total Gastado:</span>
                    <span className="font-medium">${supplier.totalSpent.toFixed(2)}</span>
                  </div>
                  {supplier.lastOrderDate && (
                    <div className="flex justify-between text-sm">
                      <span className="text-gray-500">Última Orden:</span>
                      <span className="font-medium">
                        {new Date(supplier.lastOrderDate).toLocaleDateString()}
                      </span>
                    </div>
                  )}
                </div>

                <div className="mt-4">
                  <button
                    onClick={() => {
                      setSelectedSupplier(supplier);
                      fetchSupplierProducts(supplier.id);
                    }}
                    className="w-full bg-gray-100 text-gray-700 px-4 py-2 rounded-md hover:bg-gray-200"
                  >
                    Ver Productos
                  </button>
                </div>

                <div className="mt-2">
                  <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                    supplier.isActive 
                      ? 'bg-green-100 text-green-800' 
                      : 'bg-red-100 text-red-800'
                  }`}>
                    {supplier.isActive ? 'Activo' : 'Inactivo'}
                  </span>
                </div>
              </div>
            ))}
          </div>

          {suppliers.length === 0 && (
            <div className="text-center py-12">
              <p className="text-gray-500 text-lg">No hay proveedores registrados</p>
              <button
                onClick={() => setShowAddModal(true)}
                className="mt-4 bg-blue-600 text-white px-6 py-3 rounded-md hover:bg-blue-700"
              >
                Agregar Primer Proveedor
              </button>
            </div>
          )}
        </div>
      )}

      {/* Performance Tab */}
      {activeTab === 'performance' && (
        <div className="space-y-6">
          <h2 className="text-xl font-semibold text-gray-900">Rendimiento de Proveedores</h2>
          
          {/* Top Suppliers */}
          <div className="bg-white rounded-lg shadow">
            <div className="px-6 py-4 border-b border-gray-200">
              <h3 className="text-lg font-medium text-gray-900">🏆 Mejores Proveedores</h3>
            </div>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Proveedor
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Rating
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Total Órdenes
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Total Gastado
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Promedio por Orden
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {suppliers
                    .sort((a, b) => b.totalSpent - a.totalSpent)
                    .slice(0, 10)
                    .map((supplier) => (
                      <tr key={supplier.id}>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">{supplier.name}</div>
                          <div className="text-sm text-gray-500">{supplier.code}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{getRatingStars(supplier.rating)}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{supplier.totalOrders}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">${supplier.totalSpent.toFixed(2)}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">
                            ${supplier.totalOrders > 0 ? (supplier.totalSpent / supplier.totalOrders).toFixed(2) : '0.00'}
                          </div>
                        </td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Add Supplier Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
          <div className="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
            <div className="mt-3">
              <h3 className="text-lg font-medium text-gray-900 mb-4">Agregar Nuevo Proveedor</h3>
              <form onSubmit={handleAddSupplier} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Nombre *</label>
                  <input
                    type="text"
                    required
                    value={newSupplier.name}
                    onChange={(e) => setNewSupplier({...newSupplier, name: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Código *</label>
                  <input
                    type="text"
                    required
                    value={newSupplier.code}
                    onChange={(e) => setNewSupplier({...newSupplier, code: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Persona de Contacto</label>
                  <input
                    type="text"
                    value={newSupplier.contactPerson}
                    onChange={(e) => setNewSupplier({...newSupplier, contactPerson: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Email</label>
                  <input
                    type="email"
                    value={newSupplier.email}
                    onChange={(e) => setNewSupplier({...newSupplier, email: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Teléfono</label>
                  <input
                    type="tel"
                    value={newSupplier.phone}
                    onChange={(e) => setNewSupplier({...newSupplier, phone: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div className="flex justify-end space-x-3 pt-4">
                  <button
                    type="button"
                    onClick={() => setShowAddModal(false)}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300"
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700"
                  >
                    Agregar
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* Edit Supplier Modal */}
      {showEditModal && selectedSupplier && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
          <div className="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
            <div className="mt-3">
              <h3 className="text-lg font-medium text-gray-900 mb-4">Editar Proveedor</h3>
              <form onSubmit={handleUpdateSupplier} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Nombre *</label>
                  <input
                    type="text"
                    required
                    value={selectedSupplier.name}
                    onChange={(e) => setSelectedSupplier({...selectedSupplier, name: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Persona de Contacto</label>
                  <input
                    type="text"
                    value={selectedSupplier.contactPerson || ''}
                    onChange={(e) => setSelectedSupplier({...selectedSupplier, contactPerson: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Email</label>
                  <input
                    type="email"
                    value={selectedSupplier.email || ''}
                    onChange={(e) => setSelectedSupplier({...selectedSupplier, email: e.target.value})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Rating</label>
                  <select
                    value={selectedSupplier.rating}
                    onChange={(e) => setSelectedSupplier({...selectedSupplier, rating: parseInt(e.target.value)})}
                    className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2"
                  >
                    {[1, 2, 3, 4, 5].map(rating => (
                      <option key={rating} value={rating}>{rating} {'⭐'.repeat(rating)}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="flex items-center">
                    <input
                      type="checkbox"
                      checked={selectedSupplier.isActive}
                      onChange={(e) => setSelectedSupplier({...selectedSupplier, isActive: e.target.checked})}
                      className="mr-2"
                    />
                    <span className="text-sm font-medium text-gray-700">Activo</span>
                  </label>
                </div>
                <div className="flex justify-end space-x-3 pt-4">
                  <button
                    type="button"
                    onClick={() => setShowEditModal(false)}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300"
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700"
                  >
                    Guardar
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* Supplier Products Modal */}
      {selectedSupplier && supplierProducts.length > 0 && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
          <div className="relative top-10 mx-auto p-5 border w-4/5 max-w-4xl shadow-lg rounded-md bg-white">
            <div className="mt-3">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-medium text-gray-900">
                  Productos de {selectedSupplier.name}
                </h3>
                <button
                  onClick={() => {
                    setSelectedSupplier(null);
                    setSupplierProducts([]);
                  }}
                  className="text-gray-400 hover:text-gray-600"
                >
                  ✕
                </button>
              </div>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Producto
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        SKU Proveedor
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Precio
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Cantidad Mín.
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Tiempo Entrega
                      </th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Estado
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {supplierProducts.map((sp) => (
                      <tr key={sp.id}>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">{sp.product.name}</div>
                          <div className="text-sm text-gray-500">{sp.product.sku}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{sp.supplierSku || 'N/A'}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">${sp.supplierPrice.toFixed(2)}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{sp.minimumOrderQuantity}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{sp.leadTimeDays} días</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="flex space-x-2">
                            {sp.isPreferred && (
                              <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                Preferido
                              </span>
                            )}
                            <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                              sp.isActive 
                                ? 'bg-blue-100 text-blue-800' 
                                : 'bg-gray-100 text-gray-800'
                            }`}>
                              {sp.isActive ? 'Activo' : 'Inactivo'}
                            </span>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default SupplierManagement;
