// tienda-frontend/src/components/ProductCard.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';
import { useNotifications } from '../context/NotificationContext';
import axios from 'axios';
import { API_BASE_URL } from '../services/api';
import ProductImage from './ProductImage';
import { Button, Card, Badge } from './ui';
import { getProductImage } from '../utils/productImages';

interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  compareAtPrice?: number;
  image: string;
  imageUrl: string;
  category: string;
  brand?: string;
  color?: string;
  size?: string;
  sku: string;
  stock: number;
  isActive: boolean;
  isFeatured: boolean;
  isNew: boolean;
  isBestseller: boolean;
  averageRating: number;
  reviewCount: number;
  tags: string[];
}

interface ProductCardProps {
  product: Product;
  viewMode: 'grid' | 'list';
  onQuickView: () => void;
  onAddToComparison: () => void;
  isInComparison: boolean;
}

const ProductCard: React.FC<ProductCardProps> = ({ 
  product, 
  viewMode, 
  onQuickView, 
  onAddToComparison, 
  isInComparison 
}) => {
  const [isInWishlist, setIsInWishlist] = useState(false);
  const [isAddingToCart, setIsAddingToCart] = useState(false);
  const navigate = useNavigate();
  const { user } = useAuth();
  const { addToCart: addToCartContext } = useCart();
  const { addNotification } = useNotifications();

  const addToWishlist = async () => {
    try {
      if (!user) {
        alert('Debes iniciar sesión para agregar a favoritos');
        navigate('/login');
        return;
      }

      const token = localStorage.getItem('token');
      
      // Intentar con diferentes endpoints posibles
      try {
        await axios.post(`${API_BASE_URL}/wishlist`, {
          productId: product.id
        }, {
          headers: { Authorization: `Bearer ${token}` }
        });
      } catch (error: any) {
        // Si falla, intentar con endpoint alternativo
        if (error.response?.status === 404) {
          await axios.post(`${API_BASE_URL}/products/wishlist`, {
            productId: product.id
          }, {
            headers: { Authorization: `Bearer ${token}` }
          });
        } else {
          throw error;
        }
      }
      
      setIsInWishlist(true);
      addNotification({
        type: 'success',
        title: 'Agregado a Favoritos',
        message: `${product.name} se agregó a tu lista de favoritos`,
        duration: 3000
      });
    } catch (error: any) {
      if (error.response?.status === 401) {
        alert('Tu sesión ha expirado. Por favor, inicia sesión nuevamente.');
        navigate('/login');
      } else {
        alert('Error al agregar a favoritos. Inténtalo de nuevo.');
      }
    }
  };

  const addToCart = async () => {
    try {
      setIsAddingToCart(true);
      
      if (!user) {
        addNotification({
          type: 'warning',
          title: 'Inicia Sesión',
          message: 'Debes iniciar sesión para agregar productos al carrito',
          duration: 4000
        });
        return;
      }

      const token = localStorage.getItem('token');
      if (!token) {
        addNotification({
          type: 'warning',
          title: 'Inicia Sesión',
          message: 'Debes iniciar sesión para agregar productos al carrito',
          duration: 4000
        });
        return;
      }

      // Usar el contexto de carrito directamente
      addToCartContext(product);
      
      addNotification({
        type: 'success',
        title: 'Agregado al Carrito',
        message: `${product.name} se agregó a tu carrito`,
        duration: 3000
      });
    } catch (error: any) {
      addNotification({
        type: 'error',
        title: 'Error',
        message: 'Error al agregar al carrito. Inténtalo de nuevo.',
        duration: 4000
      });
    } finally {
      setIsAddingToCart(false);
    }
  };

  const trackView = async () => {
    try {
      const token = localStorage.getItem('token');
      if (token) {
        // Cambiar la URL relativa a la base del backend
        await axios.post(`${API_BASE_URL}/api/products/track-view`, {
          productId: product.id
        }, {
          headers: { Authorization: `Bearer ${token}` }
        });
      }
    } catch (error) {
    }
  };

  const discountPercentage = product.compareAtPrice 
    ? Math.round(((product.compareAtPrice - product.price) / product.compareAtPrice) * 100)
    : 0;

  const renderStars = (rating: number) => {
    const stars = [];
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 !== 0;
    
    for (let i = 0; i < fullStars; i++) {
      stars.push(<span key={i} className="text-yellow-400">★</span>);
    }
    
    if (hasHalfStar) {
      stars.push(<span key="half" className="text-yellow-400">☆</span>);
    }
    
    const emptyStars = 5 - Math.ceil(rating);
    for (let i = 0; i < emptyStars; i++) {
      stars.push(<span key={`empty-${i}`} className="text-gray-300">☆</span>);
    }
    
    return stars;
  };

  if (viewMode === 'list') {
    return (
      <Card className="flex gap-4 hover:shadow-xl transition-all duration-300" padding="md">
        <div className="relative w-32 h-32 flex-shrink-0 cursor-pointer" onClick={() => { trackView(); onQuickView(); }}>
          <ProductImage
            src={getProductImage(product.name, product.category, product.imageUrl || product.image)}
            alt={product.name}
            className="w-full h-full object-cover rounded-lg"
            loading="lazy"
          />
          
          {/* Badges */}
          <div className="absolute top-2 left-2 flex flex-col gap-1">
{product.isNew && <Badge variant="success" size="sm" icon="✨">Nuevo</Badge>}
            {product.isBestseller && <Badge variant="primary" size="sm" icon="🔥">Bestseller</Badge>}
            {discountPercentage > 0 && <Badge variant="danger" size="sm">-{discountPercentage}%</Badge>}
          </div>
        </div>

        <div className="flex-1 flex flex-col justify-between">
          <div>
            <div className="flex items-start justify-between">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 hover:text-primary cursor-pointer transition-colors"
                    onClick={() => { trackView(); navigate(`/product/${product.id}`); }}>
                  {product.name}
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">{product.brand}</p>
                <p className="text-sm text-gray-700 dark:text-gray-300 line-clamp-2">{product.description}</p>
              </div>
              
              <div className="flex flex-col items-end gap-2">
                <button
                  onClick={(e) => { e?.stopPropagation(); addToWishlist(); }}
                  className={`p-2 rounded-full transition-all duration-200 hover:scale-110 ${
                    isInWishlist 
                      ? 'text-accent bg-accent-light/20' 
                      : 'text-gray-400 dark:text-gray-500 hover:text-accent hover:bg-accent-light/20'
                  }`}
                >
                  {isInWishlist ? '❤️' : '🤍'}
                </button>
                <button
                  onClick={(e) => { e?.stopPropagation(); onAddToComparison(); }}
                  className={`p-2 rounded-full transition-all duration-200 hover:scale-110 ${
                    isInComparison 
                      ? 'text-primary bg-primary-light/20' 
                      : 'text-gray-400 dark:text-gray-500 hover:text-primary hover:bg-primary-light/20'
                  }`}
                  title="Comparar"
                >
                  ⚖️
                </button>
              </div>
            </div>

            <div className="flex items-center gap-2 mb-2">
              <div className="flex items-center text-yellow-400">
                {renderStars(product.averageRating)}
              </div>
              <span className="text-sm text-gray-500 dark:text-gray-400">({product.reviewCount})</span>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-xl font-bold text-gray-900 dark:text-gray-100">S/ {product.price.toFixed(2)}</span>
              {product.compareAtPrice && (
                <span className="text-sm text-gray-500 dark:text-gray-400 line-through">S/ {product.compareAtPrice.toFixed(2)}</span>
              )}
            </div>

            <div className="flex items-center gap-2">
              <Button 
                variant="outline" 
                size="sm"
                onClick={(e) => { e?.stopPropagation(); onQuickView(); }}
                icon="👁️"
                className="border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700"
              >
                Vista Rápida
              </Button>
              <Button
                onClick={(e) => { e?.stopPropagation(); addToCart(); }}
                disabled={isAddingToCart || product.stock <= 0}
                loading={isAddingToCart}
                size="sm"
                icon="🛒"
                className="btn-modern btn-modern-primary"
              >
                {product.stock <= 0 ? 'Sin Stock' : 'Agregar'}
              </Button>
            </div>
          </div>
        </div>
      </Card>
    );
  }

  // Grid view
  return (
    <Card className="overflow-hidden group hover:shadow-2xl transition-all duration-300 hover:-translate-y-1" padding="none">
      <div className="relative cursor-pointer" onClick={() => { trackView(); onQuickView(); }}>
        <ProductImage
          src={getProductImage(product.name, product.category, product.imageUrl || product.image)}
          alt={product.name}
          className="w-full h-48 group-hover:scale-105 transition-transform duration-300"
          loading="lazy"
        />
        
        {/* Badges */}
        <div className="absolute top-3 left-3 flex flex-col gap-2">
{product.isNew && <Badge variant="success" size="sm" icon="✨">Nuevo</Badge>}
          {product.isFeatured && <Badge variant="primary" size="sm" icon="⭐">Destacado</Badge>}
          {product.isBestseller && <Badge variant="primary" size="sm" icon="🔥">Bestseller</Badge>}
          {discountPercentage > 0 && <Badge variant="danger" size="sm">-{discountPercentage}%</Badge>}
        </div>

        {/* Action buttons */}
        <div className="absolute top-3 right-3 flex flex-col gap-2 opacity-0 group-hover:opacity-100 transition-all duration-300 transform translate-x-2 group-hover:translate-x-0">
          <button
            onClick={(e) => { e.stopPropagation(); addToWishlist(); }}
            className={`p-3 rounded-full backdrop-blur-sm shadow-md transition-all duration-200 hover:scale-110 ${
              isInWishlist 
                ? 'bg-accent text-white shadow-accent/25' 
                : 'bg-gray-50/80 dark:bg-gray-800/80 text-gray-700 dark:text-gray-200 hover:bg-accent-light/20 hover:text-accent'
            }`}
          >
            {isInWishlist ? '❤️' : '🤍'}
          </button>
          <button
            onClick={(e) => { e.stopPropagation(); onAddToComparison(); }}
            className={`p-3 rounded-full backdrop-blur-sm shadow-md transition-all duration-200 hover:scale-110 ${
              isInComparison 
                ? 'bg-primary text-white shadow-primary/25' 
                : 'bg-gray-50/80 dark:bg-gray-800/80 text-gray-700 dark:text-gray-200 hover:bg-primary-light/20 hover:text-primary'
            }`}
            title="Comparar"
          >
            ⚖️
          </button>
          <button
            onClick={(e) => { e.stopPropagation(); onQuickView(); }}
            className="p-3 rounded-full bg-white/80 backdrop-blur-md text-gray-600 hover:bg-purple-50 hover:text-purple-500 shadow-lg transition-all duration-200 hover:scale-110"
            title="Vista Rápida"
          >
            �️
          </button>
        </div>

        {/* Stock indicator */}
        {product.stock <= 0 && (
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center">
            <Badge variant="danger" size="lg" icon="⚠️">Sin Stock</Badge>
          </div>
        )}

        {/* Quick add to cart overlay */}
        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-4 opacity-0 group-hover:opacity-100 transition-all duration-300 transform translate-y-4 group-hover:translate-y-0">
          <Button
            onClick={(e) => { e?.stopPropagation(); addToCart(); }}
            disabled={isAddingToCart || product.stock <= 0}
            loading={isAddingToCart}
            fullWidth
            className="btn-modern btn-modern-primary bg-primary/90 hover:bg-primary text-white"
            size="sm"
            icon="🛒"
          >
            {product.stock <= 0 ? 'Sin Stock' : 'Agregar al Carrito'}
          </Button>
        </div>
      </div>

      <div className="p-4">
        <div className="mb-3">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 hover:text-primary cursor-pointer line-clamp-2 transition-colors duration-200"
              onClick={() => { trackView(); navigate(`/product/${product.id}`); }}>
            {product.name}
          </h3>
          {product.brand && (
            <p className="text-sm text-gray-600 dark:text-gray-400 font-medium">{product.brand}</p>
          )}
        </div>

        <div className="flex items-center gap-2 mb-3">
          <div className="flex items-center text-yellow-400">
            {renderStars(product.averageRating)}
          </div>
          <span className="text-sm text-gray-500 dark:text-gray-400">({product.reviewCount})</span>
        </div>

        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <span className="text-xl font-bold text-gray-900 dark:text-gray-100">S/ {product.price.toFixed(2)}</span>
            {product.compareAtPrice && (
              <span className="text-sm text-gray-500 dark:text-gray-400 line-through">S/ {product.compareAtPrice.toFixed(2)}</span>
            )}
          </div>
          
          {product.stock > 0 && product.stock <= 5 && (
            <Badge variant="warning" size="sm" icon="⚠️">
              Solo {product.stock} disponibles
            </Badge>
          )}
        </div>

        <div className="flex gap-2">
          <Button
            onClick={() => { trackView(); navigate(`/product/${product.id}`); }}
            variant="outline"
            size="sm"
            fullWidth
            icon="👁️"
            className="border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700"
          >
            Ver Detalles
          </Button>
          <Button
            onClick={(e) => { e?.stopPropagation(); addToCart(); }}
            disabled={isAddingToCart || product.stock <= 0}
            loading={isAddingToCart}
            size="sm"
            fullWidth
            className="btn-modern btn-modern-primary"
            icon="🛒"
          >
            {product.stock <= 0 ? 'Sin Stock' : 'Agregar'}
          </Button>
        </div>
      </div>
    </Card>
  );
};

export default ProductCard;

// tienda-frontend/src/components/ProductCard.vue
<template>
  <div :class="computedClasses" class="group relative">
    <div class="relative h-72 bg-gradient-to-br from-purple-600/20 to-pink-600/20 overflow-hidden group-hover:scale-110 transition-transform duration-500">
      <img
        :src="getProductImageUrl(product)"
        :alt="product.name"
        class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
        loading="lazy"
      />
      
      <div class="absolute inset-0 bg-black/50 backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-all duration-300 flex items-center justify-center">
        <div class="flex gap-3">
          <Button
            @click="$emit('quick-view', product)"
            size="sm"
            icon="👁️"
            class="bg-white text-gray-900 hover:bg-gray-100 font-semibold"
          >
            Ver
          </Button>
          <Button
            @click="$emit('add-to-comparison', product)"
            size="sm"
            icon="⚖️"
            class="bg-gradient-to-r from-purple-500 to-pink-500 text-white hover:from-purple-600 hover:to-pink-600 font-semibold"
          >
            Comparar
          </Button>
        </div>
      </div>

      <div class="absolute top-4 left-4 flex flex-col gap-2">
        <Badge v-if="product.isFeatured" variant="primary" size="sm">⭐ Destacado</Badge>
        <Badge v-if="product.isNew" variant="info" size="sm">🆕 Nuevo</Badge>
        <Badge v-if="product.isOnSale" variant="danger" size="sm">🏷️ Oferta</Badge>
        <Badge v-if="product.isBestseller" variant="warning" size="sm pulse">🔥 Bestseller</Badge>
        <Badge v-if="product.stock <= 5 && product.stock > 0" variant="warning" size="sm">¡Solo {{ product.stock }}!</Badge>
        <Badge v-if="product.stock === 0" variant="danger" size="sm">Agotado</Badge>
      </div>
    </div>

    <div class="p-6 space-y-3">
      <h3 class="text-lg font-bold text-white line-clamp-2 group-hover:text-purple-400 transition-colors cursor-pointer" @click="$emit('navigate', product.id)">
        {{ product.name }}
      </h3>
      <p class="text-gray-400 text-sm line-clamp-2">{{ product.description }}</p>

      <div class="flex items-center justify-between pt-2 border-t border-white/10">
        <span class="text-2xl font-bold font-mono tabular-nums text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text">
          S/ {{ typeof product.price === 'number' ? product.price.toFixed(2) : product.price }}
        </span>
        <div class="flex flex-col items-end">
          <span v-if="product.reviewCount" class="flex items-center gap-1">
            <span class="text-yellow-400 text-sm">★ {{ Number(product.averageRating || 0).toFixed(1) }}</span>
            <span class="text-gray-500 text-xs">({{ product.reviewCount }})</span>
          </span>
        </div>
      </div>

      <div class="flex gap-2 pt-2">
        <Button
          variant="outline"
          size="sm"
          full-width
          class="text-white border-white/30 hover:bg-white/10"
          @click="$emit('navigate', product.id)"
        >
          Detalles
        </Button>
        <Button
          size="sm"
          full-width
          icon="🛒"
          class="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white"
          :disabled="product.stock <= 0"
          @click="$emit('add-to-cart', product)"
        >
          {{ product.stock <= 0 ? 'Agotado' : 'Agregar' }}
        </Button>
      </div>
    </div>

    <div v-if="isInComparison" class="absolute bottom-4 right-4">
      <Badge variant="primary" size="sm" icon="✓">En comparación</Badge>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Product } from '../types'
import Button from '../components/ui/Button.vue'
import Badge from '../components/ui/Badge.vue'
import { getProductImage } from '../utils/productImages'

interface Props {
  product: Product
  viewMode?: 'grid' | 'list'
  isInComparison?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  viewMode: 'grid',
  isInComparison: false
})

const emit = defineEmits<{
  'add-to-cart': [product: Product]
  'quick-view': [product: Product]
  'add-to-comparison': [product: Product]
  navigate: [id: number]
}>()

const computedClasses = computed(() => {
  const base = 'bg-white/10 backdrop-blur-xl rounded-2xl overflow-hidden border border-white/20 hover:shadow-2xl hover:border-purple-500/50 transition-all duration-500 animate-fade-in-up'
  return props.viewMode === 'list' ? `${base} flex` : base
})

const getProductImageUrl = (product: Product): string => {
  return getProductImage(product.name, product.category, product.imageUrl)
}
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.animate-fade-in-up {
  animation: fadeInUp 0.6s ease-out forwards;
  opacity: 0;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
